using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;

namespace StarSimCore.Application.Localization;

public sealed class LocalizationService : INotifyPropertyChanged
{
    private static readonly string LanguagePreferencePath = Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),
        "StarSimCore",
        "language.txt");
    private static readonly Lazy<LocalizationService> instance = new(() => new LocalizationService());
    public static LocalizationService Instance => instance.Value;

    public const string English = "en-US";
    public const string Romanian = "ro-RO";

    public static IReadOnlyList<string> SupportedLanguages { get; } = [English, Romanian];

    public static IReadOnlyList<LanguageOption> SupportedLanguageOptions { get; } =
    [
        new(English, "English"),
        new(Romanian, "Română")
    ];

    public record LanguageOption(string Code, string DisplayName);

    private string currentLanguage = English;

    public event PropertyChangedEventHandler? PropertyChanged;
    public event EventHandler? LanguageChanged;

    public LocalizationService()
    {
        // Use the explicit saved preference first, then the OS language on first run.
        try
        {
            if (File.Exists(LanguagePreferencePath))
            {
                var saved = File.ReadAllText(LanguagePreferencePath).Trim();
                if (SupportedLanguages.Contains(saved, StringComparer.OrdinalIgnoreCase))
                {
                    currentLanguage = string.Equals(saved, Romanian, StringComparison.OrdinalIgnoreCase)
                        ? Romanian
                        : English;
                    CultureInfo.CurrentUICulture = new CultureInfo(currentLanguage);
                    return;
                }
            }

            var uiCulture = CultureInfo.CurrentUICulture;
            if (uiCulture.TwoLetterISOLanguageName.Equals("ro", StringComparison.OrdinalIgnoreCase) ||
                uiCulture.Name.StartsWith("ro", StringComparison.OrdinalIgnoreCase))
            {
                currentLanguage = Romanian;
            }
            else
            {
                currentLanguage = English;
            }
        }
        catch
        {
            currentLanguage = English;
        }
    }

    public string CurrentLanguage
    {
        get => currentLanguage;
        set
        {
            var validated = string.Equals(value, Romanian, StringComparison.OrdinalIgnoreCase)
                ? Romanian
                : English;

            if (currentLanguage == validated) return;
            currentLanguage = validated;

            try
            {
                CultureInfo.CurrentUICulture = new CultureInfo(validated);
                var directory = Path.GetDirectoryName(LanguagePreferencePath);
                if (!string.IsNullOrEmpty(directory)) Directory.CreateDirectory(directory);
                File.WriteAllText(LanguagePreferencePath, validated);
            }
            catch
            {
                // Fallback safe
            }

            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(CurrentLanguage)));
            // Keep direct indexer bindings compatible with both CLR/Avalonia
            // (Item) and the conventional binding-engine name (Item[]).
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item"));
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
            LanguageChanged?.Invoke(this, EventArgs.Empty);
        }
    }

    public string this[string key] => GetString(key);

    public string GetString(string key, params object[] args)
    {
        if (string.IsNullOrEmpty(key)) return string.Empty;

        var catalog = currentLanguage == Romanian ? RomanianCatalog : EnglishCatalog;

        if (!catalog.TryGetValue(key, out var template))
        {
            // Fallback to English if Romanian missing
            if (currentLanguage != English && EnglishCatalog.TryGetValue(key, out var fallback))
            {
                template = fallback;
            }
            else
            {
                Debug.WriteLine($"[Localization WARNING] Missing translation key: '{key}' for language '{currentLanguage}'.");
                return $"[[{key}]]";
            }
        }

        if (args is { Length: > 0 })
        {
            try
            {
                return string.Format(CultureInfo.InvariantCulture, template, args);
            }
            catch
            {
                return template;
            }
        }

        return template;
    }

    public string GetStringOrDefault(string key, string fallback)
    {
        var catalog = currentLanguage == Romanian ? RomanianCatalog : EnglishCatalog;
        if (catalog.TryGetValue(key, out var value)) return value;
        if (EnglishCatalog.TryGetValue(key, out value)) return value;
        return fallback;
    }

    public static IReadOnlyDictionary<string, string> EnglishCatalog { get; } = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        // App & Toolbar
        ["App.Title"] = "StarSim Core",
        ["App.Subtitle"] = "ASTROPHOTOGRAPHY IMAGING",
        ["Toolbar.OpenImage"] = "▣  Open Image",
        ["Toolbar.OpenImage.Tip"] = "Open an 8/16-bit TIFF or PNG without modifying it.",
        ["Toolbar.OpenProject"] = "⎘  Open Project",
        ["Toolbar.OpenProject.Tip"] = "Open a .starsim project file.",
        ["Toolbar.SaveProject"] = "💾  Save Project",
        ["Toolbar.SaveProject.Tip"] = "Save current state to a .starsim project file.",
        ["Toolbar.Undo.Tip"] = "Undo the last parameter-state command.",
        ["Toolbar.Redo.Tip"] = "Redo the last parameter-state command.",
        ["Toolbar.BeforeAfter"] = "◧  Before / After",
        ["Toolbar.BeforeAfter.Tip"] = "Drag the vertical divider to compare Original and Processed.",
        ["Toolbar.ZoomIn.Tip"] = "Zoom in",
        ["Toolbar.ZoomOut.Tip"] = "Zoom out",
        ["Toolbar.Fit"] = "⛶  Fit",
        ["Toolbar.Fit.Tip"] = "Fit the image to the viewer",
        ["Toolbar.Export"] = "⇧  Export…",
        ["Toolbar.Export.Tip"] = "Export full-resolution 16-bit TIFF or 8/16-bit PNG.",
        ["Toolbar.Performance"] = "⚙  Performance",
        ["Toolbar.Performance.Tip"] = "CPU, memory and interactive preview limits",

        // Menu Bar
        ["Menu.File"] = "_File",
        ["Menu.File.OpenImage"] = "_Open Image…",
        ["Menu.File.OpenProject"] = "Open _Project…",
        ["Menu.File.SaveProject"] = "_Save Project",
        ["Menu.File.SaveProjectAs"] = "Save Project _As…",
        ["Menu.File.Export"] = "_Export Image…",
        ["Menu.File.Exit"] = "E_xit",
        ["Menu.Edit"] = "_Edit",
        ["Menu.Edit.Undo"] = "_Undo",
        ["Menu.Edit.Redo"] = "_Redo",
        ["Menu.Edit.ResetAll"] = "Reset _All Processors",
        ["Menu.View"] = "_View",
        ["Menu.View.Fit"] = "_Fit to Viewer",
        ["Menu.View.ZoomIn"] = "Zoom _In",
        ["Menu.View.ZoomOut"] = "Zoom _Out",
        ["Menu.View.BeforeAfter"] = "_Before / After Comparison",
        ["Menu.View.Beginner"] = "_Beginner Mode",
        ["Menu.View.Expert"] = "_Expert Mode",
        ["Menu.Process"] = "_Process",
        ["Menu.Presets"] = "P_resets",
        ["Menu.Settings"] = "_Settings",
        ["Menu.Settings.Language"] = "Language / Limbă",
        ["Menu.Settings.Performance"] = "_Performance & Hardware Limits…",
        ["Menu.Help"] = "_Help",
        ["Menu.Help.Guide"] = "_User Guide…",
        ["Menu.Help.About"] = "_About StarSim Core…",

        // Modes
        ["Mode.Beginner"] = "Beginner",
        ["Mode.Expert"] = "Expert",

        // Viewer
        ["Viewer.Title"] = "VIEWER",
        ["Viewer.SourcePreview"] = "Source preview",
        ["Viewer.Fit"] = "FIT",
        ["Viewer.NoImage"] = "No image loaded",
        ["Viewer.NoImageHint"] = "Open an already stacked TIFF or PNG to begin",
        ["Viewer.Original"] = "ORIGINAL",
        ["Viewer.Processed"] = "PROCESSED",

        // Categories
        ["Category.Alignment"] = "Alignment",
        ["Category.Restoration"] = "Restoration",
        ["Category.Detail"] = "Detail",
        ["Category.AdvancedSharpening"] = "Advanced Sharpening",
        ["Category.Color"] = "Color",
        ["Category.Tone"] = "Tone",

        // Wavelets V2
        ["Wavelets.Title"] = "6-Scale Wavelet Detail",
        ["Wavelets.Mode.Classic"] = "Classic",
        ["Wavelets.Mode.Advanced"] = "Advanced",
        ["Wavelets.GlobalStrength"] = "Global Strength",
        ["Wavelets.InitialWidth"] = "Initial Width",
        ["Wavelets.Linked"] = "Linked Wavelets",
        ["Wavelets.ResetAll"] = "Reset Wavelets",
        ["Wavelets.ResetLayer"] = "Reset",
        ["Wavelets.Solo"] = "Solo",
        ["Wavelets.Info.Title"] = "What are wavelets?",
        ["Wavelets.Info.Body"] = "Wavelets recursively decompose the planetary image into 6 Gaussian spatial scales. Sliders 1 to 6 directly control progressively broader detail bands; Advanced width, denoise and threshold controls remain independent.",
        ["Wavelets.Layer1.Name"] = "Layer 1 — Ultra Fine",
        ["Wavelets.Layer1.Help"] = "Enhances the smallest visible structures. Useful for fine planetary texture. High values may amplify noise or ringing.",
        ["Wavelets.Layer2.Name"] = "Layer 2 — Fine",
        ["Wavelets.Layer2.Help"] = "Enhances fine surface details, small craters, festoons, and sharp planetary boundaries.",
        ["Wavelets.Layer3.Name"] = "Layer 3 — Medium-Fine",
        ["Wavelets.Layer3.Help"] = "Enhances intermediate planetary markings, rift systems, and cloud band borders.",
        ["Wavelets.Layer4.Name"] = "Layer 4 — Medium",
        ["Wavelets.Layer4.Help"] = "Enhances primary planetary belts, large craters, and prominent albedo features.",
        ["Wavelets.Layer5.Name"] = "Layer 5 — Large",
        ["Wavelets.Layer5.Help"] = "Enhances broad regional contrast, large-scale storm features, and polar hoods.",
        ["Wavelets.Layer6.Name"] = "Layer 6 — Structure",
        ["Wavelets.Layer6.Help"] = "Enhances global disk brightness distributions and broad planetary gradients.",
        ["Wavelets.Param.EnhancementFactor"] = "Enhancement",
        ["Wavelets.Param.GaussianWidth"] = "Gaussian Width",
        ["Wavelets.Param.Denoise"] = "Denoise",
        ["Wavelets.Param.Threshold"] = "Threshold",

        // Modules
        ["Module.RgbAlign"] = "RGB Align",
        ["Module.NoiseReduction"] = "Noise Reduction",
        ["Module.RichardsonLucy"] = "Deconvolution",
        ["Module.Deringing"] = "Deringing / Halo Protection",
        ["Module.Wavelet"] = "Wavelet Multiscale Detail",
        ["Module.LocalDetail"] = "Local Contrast & Detail",
        ["Module.UnsharpMask"] = "Unsharp Mask",
        ["Module.MultiScaleSharpen"] = "Multi-scale Sharpening",
        ["Module.AdvancedColor"] = "Advanced Color",
        ["Module.RgbBalance"] = "RGB Channel Balance",
        ["Module.Saturation"] = "Saturation",
        ["Module.AdvancedTone"] = "Advanced Tone",
        ["Module.Exposure"] = "Brightness / Exposure",
        ["Module.Contrast"] = "Contrast",
        ["Module.Gamma"] = "Gamma",
        ["Module.RgbAlign.Description"] = "Align color channels with sub-pixel precision",
        ["Module.NoiseReduction.Description"] = "Reduce luma and chroma noise while preserving detail",
        ["Module.RichardsonLucy.Description"] = "Reduce optical blur with iterative restoration",
        ["Module.Deringing.Description"] = "Suppress ringing and protect high-contrast edges",
        ["Module.Wavelet.Description"] = "Enhance fine detail directly across six spatial scales",
        ["Module.LocalDetail.Description"] = "Enhance microcontrast and mid-scale structure",
        ["Module.UnsharpMask.Description"] = "Classic radius-based edge enhancement",
        ["Module.MultiScaleSharpen.Description"] = "Combine fine and broad sharpening scales",
        ["Module.AdvancedColor.Description"] = "White balance, temperature, tint and vibrance",
        ["Module.RgbBalance.Description"] = "Balance red, green and blue channel gain",
        ["Module.Saturation.Description"] = "Control global color intensity",
        ["Module.AdvancedTone.Description"] = "Black, white, shadow and highlight shaping",
        ["Module.Exposure.Description"] = "Adjust linear scene brightness in stops",
        ["Module.Contrast.Description"] = "Expand or compress tonal separation",
        ["Module.Gamma.Description"] = "Shape midtones without changing endpoints",

        // Warnings
        ["Warning.MultiSharpening"] = "Multiple detail-enhancement engines are active simultaneously (Wavelets + Sharpening/RL). This may increase ringing or oversharpening.",

        // Processing & Errors
        ["Processing.InProgress"] = "Processing…",
        ["Processing.Complete"] = "Complete",
        ["Processing.Cancelled"] = "Cancelled",
        ["Processing.OpeningImage"] = "Opening image…",
        ["Processing.Cancel"] = "Cancel",
        ["Processing.LatestPreviewVisible"] = "The latest valid preview remains visible while processing.",
        ["Error.ProcessingFailed"] = "Processing Error",
        ["Error.TechnicalDetails"] = "Technical details",
        ["Error.CopyDetails"] = "Copy details",
        ["Error.OpenLogFolder"] = "Open log folder",
        ["Error.NativeOperationFailed"] = "Native operation failed",

        // Beginner Mode
        ["Beginner.Title"] = "Beginner Mode",
        ["Beginner.Subtitle"] = "Simple controls. Shared mathematical state.",
        ["Beginner.Target"] = "TARGET",
        ["Beginner.TargetQuestion"] = "What did you image?",
        ["Beginner.Preset"] = "PRESET",
        ["Beginner.PresetQuestion"] = "Choose a starting point",
        ["Beginner.ApplyPreset"] = "Apply Preset",
        ["Beginner.Adjustments"] = "ADJUSTMENTS",
        ["Beginner.PresetStrength"] = "Preset Strength",
        ["Beginner.Detail"] = "Detail",
        ["Beginner.NoiseReduction"] = "Noise Reduction",
        ["Beginner.Color"] = "Color",
        ["Beginner.Brightness"] = "Brightness",
        ["Beginner.Contrast"] = "Contrast",
        ["Beginner.ColorPreset"] = "COLOR PRESET",
        ["Beginner.AutoRgbBalance"] = "Auto RGB Balance",

        // Expert Mode
        ["Expert.Histogram"] = "Histogram",
        ["Expert.ProcessModules"] = "PROCESS MODULES",
        ["Expert.ModuleHint"] = "Click module to configure in precision window",
        ["Expert.ResetAll"] = "Reset All",
        ["Expert.ResetCategory"] = "Reset Category",
        ["Expert.ResetModule"] = "Reset",
        ["Expert.Configure"] = "⚙ Configure…",
        ["Expert.Parameters"] = "{0} parameters",
        ["Expert.EnabledCount"] = "{0}/{1} active",

        // Precision Tool Window
        ["ToolWindow.Enabled"] = "Enabled",
        ["ToolWindow.ResetModule"] = "Reset Module",
        ["ToolWindow.PrecisionHint"] = "Adjust parameters with millimetric precision. Changes update live in the viewer.",
        ["ToolWindow.Close"] = "Close",

        // Targets
        ["Target.Jupiter"] = "Jupiter",
        ["Target.Saturn"] = "Saturn",
        ["Target.Mars"] = "Mars",
        ["Target.Venus"] = "Venus",
        ["Target.Moon"] = "Moon",
        ["Target.Solar"] = "Solar",
        ["Target.Generic"] = "Generic",

        // Presets
        ["Preset.Natural"] = "Natural",
        ["Preset.Balanced"] = "Balanced",
        ["Preset.Detailed"] = "Detailed",
        ["Preset.Strong"] = "Strong",

        // Color Presets
        ["ColorPreset.Natural"] = "Natural",
        ["ColorPreset.Neutral"] = "Neutral",
        ["ColorPreset.Warm"] = "Warm",
        ["ColorPreset.Vivid"] = "Vivid",

        // Performance Profiles
        ["Performance.Profile.Balanced"] = "Balanced",
        ["Performance.Profile.HighThroughput"] = "High Throughput",
        ["Performance.Profile.LowMemory"] = "Low Memory",
        ["Performance.Profile.PowerSaver"] = "Power Saver",

        // Settings Dialog
        ["Settings.Title"] = "Performance & Hardware Limits",
        ["Settings.Language"] = "Language",

        // Complete application shell
        ["Menu.View.FullScreen"] = "_Full Screen",
        ["Menu.Process.Wavelet"] = "Wavelet Multiscale Detail…",
        ["Menu.Process.RichardsonLucy"] = "Richardson-Lucy Deconvolution…",
        ["Menu.Process.NoiseReduction"] = "Noise Reduction…",
        ["Menu.Process.LocalDetail"] = "Local Contrast & Detail…",
        ["Menu.Process.UnsharpMask"] = "Unsharp Mask…",
        ["Menu.Process.MultiScaleSharpen"] = "Multi-scale Sharpening…",
        ["Menu.Process.Deringing"] = "Deringing / Halo Protection…",
        ["Menu.Process.RgbAlign"] = "RGB Channel Alignment…",
        ["Menu.Process.AdvancedColor"] = "Advanced Color & Balance…",
        ["Menu.Process.RgbBalance"] = "RGB Balance…",
        ["Menu.Process.Saturation"] = "Saturation…",
        ["Menu.Process.AdvancedTone"] = "Advanced Tone & Curves…",
        ["Menu.Process.Exposure"] = "Brightness / Exposure…",
        ["Menu.Process.Contrast"] = "Contrast…",
        ["Menu.Process.Gamma"] = "Gamma…",
        ["Menu.Presets.SaveCustom"] = "Save Custom Preset…",
        ["Menu.Plugins"] = "Pl_ugins",
        ["Menu.Plugins.Manager"] = "Plugin _Manager…",
        ["Menu.Plugins.Install"] = "_Install Plugin…",
        ["Menu.Plugins.DeveloperGuide"] = "Plugin Developer _Guide…",
        ["Toolbar.OpenShort"] = "▱  Open",
        ["Toolbar.SaveShort"] = "▣  Save",
        ["Toolbar.Undo"] = "↶  Undo",
        ["Toolbar.Redo"] = "↷  Redo",
        ["Toolbar.Compare"] = "◧  Compare",
        ["Toolbar.Compare.Tip"] = "Show or hide the draggable before/after divider",
        ["Viewer.ImageViewer"] = "Image Viewer",
        ["Viewer.FullScreen.Tip"] = "Full screen",
        ["Viewer.PixelHint"] = "Move over the image to inspect pixels",
        ["Viewer.OutsideImage"] = "Outside image",
        ["Viewer.Gray"] = "Gray",
        ["Viewer.ZoomLabel"] = "Zoom:",
        ["Histogram.NoData"] = "NO IMAGE DATA",
        ["Histogram.LiveDescription"] = "Live RGB distribution for the current processed image",
        ["Histogram.OpenImageHint"] = "Open an image to populate the histogram.",
        ["Histogram.Title"] = "StarSim Core — Histogram",
        ["Histogram.OpenSeparate.Tip"] = "Open histogram in a separate window",
        ["Panel.Processing"] = "Processing",
        ["Panel.SearchModules"] = "Search modules…",
        ["Panel.BeginnerWorkflow"] = "BEGINNER WORKFLOW",
        ["Panel.ModuleCount"] = "{0} modules",
        ["Panel.OpenSeparate.Tip"] = "Open this module in a separate panel",
        ["Panel.OpenSeparate"] = "Open separate panel  ⧉",
        ["Panel.AdvancedDiagnostic"] = "Advanced / Diagnostic…  ⧉",
        ["Group.DETAIL"] = "DETAIL",
        ["Group.COLOR"] = "COLOR",
        ["Group.TONE"] = "TONE",
        ["Group.PLUGINS"] = "PLUGINS",

        // Common actions and dialogs
        ["Common.Close"] = "Close",
        ["Common.Cancel"] = "Cancel",
        ["Common.Automatic"] = "Automatic",
        ["Common.Auto"] = "Auto",
        ["Common.Manual"] = "Manual",
        ["Common.Refresh"] = "Refresh",
        ["Dialog.RelocateSource.Title"] = "Source Image Relocation",
        ["Dialog.RelocateSource.Locate"] = "Locate Source File…",
        ["Dialog.CustomPreset.Title"] = "Save Custom Preset",
        ["Dialog.CustomPreset.Name"] = "Preset name",
        ["Dialog.CustomPreset.Description"] = "Description",
        ["Dialog.CustomPreset.Save"] = "Save preset",
        ["FilePicker.OpenImage"] = "Open stacked image",
        ["FilePicker.Images"] = "TIFF and PNG images",
        ["FilePicker.OpenProject"] = "Open StarSim Project",
        ["FilePicker.SaveProject"] = "Save StarSim Project",
        ["FilePicker.Projects"] = "StarSim Projects (*.starsim)",
        ["FilePicker.ExportImage"] = "Export Processed Image",
        ["FilePicker.Tiff16"] = "16-bit TIFF (*.tif, *.tiff)",
        ["FilePicker.Png"] = "PNG image (*.png)",
        ["FilePicker.LocateSource"] = "Locate Missing Source Image",
        ["FilePicker.InstallPlugin"] = "Install StarSim Core native plugin",
        ["FilePicker.PluginDll"] = "Native plugin DLL (*.dll)",
        ["FilePicker.ExportWavelet"] = "Export Wavelet Calibration Diagnostics",

        // Workflow values and summaries
        ["Target.Default"] = "Default",
        ["Preset.Default"] = "Default",
        ["ColorPreset.Default"] = "Default",
        ["Beginner.CustomModified"] = "Custom/Modified",
        ["Beginner.NeutralDescription"] = "Neutral processing state. Choose a target and preset explicitly to apply a recipe.",
        ["Beginner.PresetDescription"] = "Conservative {0} engineering starting point for the selected {1} data; intended for later calibration, not a universal scientific optimum.",
        ["Beginner.PresetDescription.Natural"] = "Gentle starting point for {0}: restrained detail and noise reduction. Press Apply Preset, then fine-tune one control at a time.",
        ["Beginner.PresetDescription.Balanced"] = "Recommended starting point for {0}: useful fine detail with controlled noise and broad structure. Press Apply Preset to preview it.",
        ["Beginner.PresetDescription.Detailed"] = "Stronger fine and medium detail for good {0} data. Watch grain and bright-edge ringing, then reduce Detail if needed.",
        ["Beginner.PresetDescription.Strong"] = "Aggressive detail for very clean, well-sampled {0} data. Check the image at 100% and back off if noise or halos appear.",
        ["Mode.BeginnerWorkspace"] = "Beginner workflow",
        ["Mode.ExpertWorkspace"] = "Expert workspace",
        ["Summary.SourceNone"] = "Source: none",
        ["Summary.Source"] = "{0}  •  {1}×{2}  •  {3}-bit {4}",
        ["Summary.NoImage"] = "No image  •  FIT  •  float32",
        ["Summary.Image"] = "{0}×{1}  •  {2} channel(s)  •  float32",
        ["Summary.AlphaIgnored"] = "Alpha detected and ignored",
        ["Summary.SourceImmutable"] = "Source pixels remain immutable",
        ["Summary.NoHistogram"] = "No histogram data",
        ["Summary.Histogram"] = "Min {0:0.000}   |   Mean {1:0.000}   |   Max {2:0.000}",
        ["Performance.Resolved"] = "{0}: {1}",
        ["Performance.Diagnostics"] = "Logical CPUs {0} • workers {1} • available RAM {2:0.0} GB • budget {3:0.0} GB • tracked {4:0} MB • pool {5:0} MB ({6} buffers, {7} reuses/{8} allocations) • jobs {9}",

        // Performance window
        ["Performance.Title"] = "StarSim Core — Performance",
        ["Performance.Header"] = "Performance",
        ["Performance.Subtitle"] = "CPU, memory and interactive preview policy",
        ["Performance.Profile"] = "Performance profile",
        ["Performance.Profile.Help"] = "Select the balance between processing throughput and UI responsiveness.",
        ["Performance.CpuThreads"] = "CPU threads",
        ["Performance.MemoryLimit"] = "Memory limit",
        ["Performance.InteractivePreview"] = "Interactive preview",
        ["Performance.PrioritizeUi"] = "Prioritize UI responsiveness",
        ["Performance.ReduceBattery"] = "Reduce CPU usage on battery",
        ["Performance.Immediate"] = "Changes are applied immediately.",
        ["Performance.Preview.Auto"] = "Auto",
        ["Performance.Preview.Full"] = "Full resolution",
        ["Performance.Preview.Half"] = "Half resolution",
        ["Performance.Preview.Quarter"] = "Quarter resolution",
        ["Performance.Profile.Eco"] = "Eco",
        ["Performance.Profile.Maximum"] = "Maximum",

        // Tool windows and wavelet diagnostics
        ["ToolWindow.Parameters"] = "PARAMETERS",
        ["ToolWindow.PluginWarning"] = "NATIVE EXTERNAL PLUGIN — NOT SANDBOXED",
        ["ToolWindow.PluginProvider"] = "External plugin: {0} {1} • {2}",
        ["ToolWindow.PluginHint"] = "This processor is supplied by a native, in-process plugin. It is not sandboxed. Editing a control activates it and updates the viewer.",
        ["ToolWindow.NoiseHint"] = "Raise Luminance or Chrominance above zero to reduce noise. Editing a control activates the module automatically.",
        ["ToolWindow.GenericHint"] = "Editing a control activates this module automatically and updates the viewer live.",
        ["ToolWindow.PluginFallbackDescription"] = "External processor supplied by {0}.",
        ["Wavelets.ToolTitle"] = "StarSim Core — Wavelet Multiscale Detail",
        ["Wavelets.ResetAll.Tip"] = "Reset all wavelet layers to neutral defaults",
        ["Wavelets.Linked.Tip"] = "Link all layer sliders together",
        ["Wavelets.Solo.Tip"] = "Solo layer preview: isolate this scale contribution",
        ["Wavelets.ResetLayer.Tip"] = "Reset this layer to neutral (1.0)",
        ["Wavelets.NudgeDown.Tip"] = "Fine nudge down (-1)",
        ["Wavelets.NudgeUp.Tip"] = "Fine nudge up (+1)",
        ["Wavelets.Diagnostic.Title"] = "Decomposition & Wavelet Diagnostic",
        ["Wavelets.Diagnostic.Backend"] = "Backend",
        ["Wavelets.Diagnostic.ScaleScheme"] = "Scale scheme",
        ["Wavelets.Diagnostic.LinearStep"] = "Linear step",
        ["Wavelets.Diagnostic.Export"] = "Export diagnostics…",
        ["Wavelets.Diagnostic.InitialStatus"] = "Exports source, D1–D6, L6, reconstruction, and deterministic calibration presets.",
        ["Wavelets.Diagnostic.Exporting"] = "Exporting wavelet diagnostics…",
        ["Wavelets.Diagnostic.Exported"] = "Diagnostics exported to {0}",
        ["Wavelets.Diagnostic.Failed"] = "Diagnostic export failed: {0}",
        ["Wavelets.Scale.Linear"] = "Linear scales",
        ["Wavelets.Scale.Dyadic"] = "Dyadic scales (2^n)",
        ["Wavelets.Backend.RecursiveGaussian"] = "Recursive Gaussian",
        ["Wavelets.Backend.AtrousB3Spline"] = "À-trous B3 spline",
        ["Wavelets.Encoding.Float32"] = "32-bit float TIFF",
        ["Wavelets.Encoding.UInt16"] = "16-bit TIFF",
        ["Wavelets.Compact.Strength"] = "Strength",
        ["Wavelets.Compact.Layer1"] = "L1 · Ultrafine",
        ["Wavelets.Compact.Layer2"] = "L2 · Fine",
        ["Wavelets.Compact.Layer3"] = "L3 · Medium-fine",
        ["Wavelets.Compact.Layer4"] = "L4 · Medium",
        ["Wavelets.Compact.Layer5"] = "L5 · Large",
        ["Wavelets.Compact.Layer6"] = "L6 · Structure",

        // Plugin manager and developer guide
        ["Plugin.Title"] = "StarSim Core — Plugin Manager",
        ["Plugin.Header"] = "Plugin Manager",
        ["Plugin.Subtitle"] = "Install, inspect and manage native processing extensions",
        ["Plugin.SecurityBadge"] = "NATIVE PLUGINS ARE NOT SANDBOXED",
        ["Plugin.Tab.Installed"] = "Installed plugins",
        ["Plugin.Tab.Developer"] = "Developer guide",
        ["Plugin.EnableStartup"] = "Enable external native plugins at startup",
        ["Plugin.ChangeRestart"] = "Changes to installation or enable state take effect after restart. Existing built-in modules are never replaced.",
        ["Plugin.Install"] = "Install plugin…",
        ["Plugin.OpenFolder"] = "Open folder",
        ["Plugin.RestartBanner"] = "Restart required — the current processing pipeline remains unchanged until StarSim Core is restarted.",
        ["Plugin.None"] = "No plugin DLLs installed",
        ["Plugin.NoneHint"] = "Install a trusted x64 DLL or copy it together with its dependencies into the plugin folder.",
        ["Plugin.Remove"] = "Remove / disable",
        ["Plugin.OpenLogs"] = "Open diagnostic logs",
        ["Plugin.Guide.Title"] = "Create a StarSim Core processing plugin",
        ["Plugin.Guide.Spec"] = "ABI v1 • native C contract • Windows x64 • float32 planar images",
        ["Plugin.Guide.OpenSdk"] = "Open packaged SDK",
        ["Plugin.Guide.OpenTutorial"] = "Open complete tutorial",
        ["Plugin.TutorialMissing"] = "The complete plugin tutorial was not found at: {0}",
        ["Plugin.Guide.Security"] = "Security: plugin DLLs execute in the StarSim Core process with the same permissions as the application. They are not sandboxed. Install only code you trust.",
        ["Plugin.Guide.Step1.Title"] = "1. Files and toolchain",
        ["Plugin.Guide.Step1.Body"] = "Use a C or C++20 compiler that produces a Windows x64 DLL. Include starsim_core_plugin.h and export the three required C entry points. The packaged SDK contains the header, sample source, CMake template and full documentation.",
        ["Plugin.Guide.Step2.Title"] = "2. Required exports",
        ["Plugin.Guide.Step2.Body"] = "Metadata declares plugin identity, processor names/categories, grayscale/RGB capabilities and every numeric parameter with default, minimum, maximum and step.",
        ["Plugin.Guide.Step3.Title"] = "3. Build the sample",
        ["Plugin.Guide.Step3.Body"] = "The resulting Release DLL is the installable plugin. Keep any third-party dependency DLLs beside it in the StarSim Core plugin folder.",
        ["Plugin.Guide.Step4.Title"] = "4. Image and memory rules",
        ["Plugin.Guide.Step4.Body"] = "The host owns all input/output buffers. A plugin reads the input planes and writes the output planes only during ssc_plugin_process; it must never retain or free host pointers. V1 output keeps the same dimensions and channel count. RGB-to-B&W processors therefore write the same luminance value into R, G and B.",
        ["Plugin.Guide.Step5.Title"] = "5. Cancellation, progress and logging",
        ["Plugin.Guide.Step5.Body"] = "Long loops must poll is_cancelled. Report a normalized 0–1 fraction and a short UTF-8 stage message. log_message entries are written to the StarSim Core diagnostic log. Never throw C++ exceptions across the C ABI.",
        ["Plugin.Guide.Step6.Title"] = "6. Install and locate the generated panel",
        ["Plugin.Guide.Step6.Body"] = "Install the DLL from the first tab, enable external plugins and restart. After validation, every exported processor appears in Expert mode under the PLUGINS group. Its sliders and separate movable panel are generated automatically from the parameter schema. Plugin processors execute after the built-in Tone group, in declared discovery order.",
        ["Plugin.Guide.SampleTitle"] = "Diagnostic sample included",
        ["Plugin.Guide.SampleBody"] = "starsim_diagnostic_plugin.dll exports Invert & Tint plus RGB to B&W Mix. The B&W Strength parameter demonstrates an automatically generated plugin slider and full pipeline/export integration.",
        ["Plugin.Footer"] = "Installed user plugins are stored separately from StarSim Core built-ins.",
        ["Plugin.Runtime.Active"] = "Runtime active • {0} plugin DLL(s), {1} processor(s), {2} rejection(s)",
        ["Plugin.Runtime.Disabled"] = "Runtime disabled for this session • enable below and restart StarSim Core",
        ["Plugin.Status.Ready"] = "Ready.",
        ["Plugin.Status.EnabledRestart"] = "External plugins enabled. Restart StarSim Core to discover installed DLLs.",
        ["Plugin.Status.DisabledRestart"] = "External plugins disabled for the next launch. Currently loaded plugins remain active until restart.",
        ["Plugin.Processors.None"] = "No processors",
        ["Plugin.Processors"] = "Processors: {0}",
        ["Plugin.State.Loaded"] = "Loaded",
        ["Plugin.State.Rejected"] = "Rejected",
        ["Plugin.State.Restart"] = "Restart required",
        ["Plugin.State.NotLoaded"] = "Not loaded",
        ["Plugin.NoProcessorsRegistered"] = "No processors registered.",
        ["Plugin.RestartDetail"] = "This DLL was installed after discovery or was not part of the active scan. Restart to validate it.",
        ["Plugin.DisabledDetail"] = "External plugin loading is disabled for this session.",
        ["Plugin.MetadataAfter"] = "Processor metadata becomes available after successful loading.",
        ["Plugin.SdkMissing"] = "SDK folder is not present in this output: {0}",
        ["Plugin.Identity.Id"] = "ID: {0}",
        ["Plugin.Identity.Author"] = "Author: {0}",
        ["Plugin.Install.NotFound"] = "Plugin file was not found: {0}",
        ["Plugin.Install.InvalidExtension"] = "StarSim Core native plugins must be Windows .dll files.",
        ["Plugin.Install.AlreadyPresent"] = "That DLL is already in the StarSim Core user plugin folder.",
        ["Plugin.Install.Success"] = "Installed '{0}'. Restart StarSim Core to validate and load it.",
        ["Plugin.Install.Failed"] = "Plugin installation failed: {0}",
        ["Plugin.Remove.Bundled"] = "Bundled/application plugins cannot be removed here. Remove them from the application package or disable external plugins globally.",
        ["Plugin.Remove.Missing"] = "The selected plugin file no longer exists.",
        ["Plugin.Remove.Success"] = "Plugin moved to '{0}'. Restart StarSim Core to remove its panel from the current session.",
        ["Plugin.Remove.Scheduled"] = "Plugin is currently in use and will be moved to the disabled archive on next startup. {0}",

        // Runtime messages
        ["Status.Ready"] = "Ready",
        ["Status.ExportStarting"] = "Starting export…",
        ["Status.ExportComplete"] = "Export complete: {0}",
        ["Status.ExportCancelled"] = "Export cancelled.",
        ["Status.ExportFailed"] = "Export failed: {0}",
        ["Export.Stage.Preparing"] = "Preparing the full-resolution pipeline…",
        ["Export.Stage.ProcessingModule"] = "Processing {0}…",
        ["Export.Stage.Encoding"] = "Encoding and writing to disk…",
        ["Export.Stage.Writing"] = "Writing export file… ({0}/{1})",
        ["Export.Stage.Complete"] = "Export complete.",
        ["Status.WaveletExported"] = "Wavelet diagnostics exported: {0}",
        ["Status.ProjectSaved"] = "Project saved: {0}",
        ["Status.CustomPresetSaved"] = "Custom preset '{0}' saved.",
        ["Status.FastPreview"] = "Fast preview — {0:0.0} ms",
        ["Status.LatestPending"] = "{0} • latest change pending",
        ["Status.ProcessingComplete"] = "Processing complete — latest state rendered",
        ["Processing.Stage.Scheduled"] = "Scheduled",
        ["Processing.Stage.LatestPendingUpdated"] = "Latest pending updated",
        ["Processing.Stage.ProcessingLatestPending"] = "Processing latest pending",
        ["Processing.Stage.PreparingPipeline"] = "Preparing pipeline",
        ["Processing.Stage.ComputingHistogram"] = "Computing histogram",
        ["Processing.Stage.PublishingPreview"] = "Publishing preview",
        ["Processing.Stage.ProcessorPipeline"] = "Processor pipeline",
        ["Processing.Stage.Histogram"] = "Histogram",
        ["Processing.Stage.PublicationGate"] = "Publication gate",
        ["Processing.Stage.Complete"] = "Complete",
        ["Processing.Stage.WaveletLayer"] = "Wavelet layer",
        ["Processing.Stage.RichardsonLucyIteration"] = "Richardson-Lucy iteration",
        ["Processing.Stage.ProcessingModule"] = "Processing {0}…",
        ["Error.NativeStopped"] = "Processing stopped unexpectedly inside the native engine.",
        ["Error.WaveletExpertOnly"] = "Wavelet Diagnostic mode is available only in Expert mode.",
        ["Error.OpenImageForWavelet"] = "Open an image before exporting wavelet diagnostics.",
        ["Error.WaveletMissing"] = "Wavelet processor is not registered.",
        ["Project.SourceMissing"] = "Source image missing at '{0}'. Locate the relocated image file.",
        ["Project.SourceMismatch"] = "Source fingerprint mismatch at '{0}'. Locate the exact original source file; the different image was not bound to the project.",
        ["Project.SourceMismatchLocated"] = "Source fingerprint mismatch. {0} Locate the exact original source file; no image has been bound to the project.",
        ["Project.IncompatibleSource"] = "Incompatible source: {0}",

        // Context menu
        ["Context.Undo"] = "Undo",
        ["Context.Redo"] = "Redo",
        ["Context.Fit"] = "Fit to viewer",
        ["Context.ZoomIn"] = "Zoom in",
        ["Context.ZoomOut"] = "Zoom out",
        ["Context.Compare"] = "Before / After comparison",
        ["Context.ResetAll"] = "Reset all processors",
        ["Context.Export"] = "Export processed image…",

        // Help and About
        ["Help.Title"] = "StarSim Core — Help & About",
        ["Help.Header"] = "StarSim Core Help",
        ["Help.Subtitle"] = "Beginner workflow, Expert pipeline, modules and plugins",
        ["Help.Version"] = "Version {0}",
        ["Help.Tab.About"] = "About",
        ["Help.Tab.Beginner"] = "Beginner workflow",
        ["Help.Tab.Expert"] = "Expert & modules",
        ["Help.Tab.Plugins"] = "Plugins",
        ["Help.About.Title"] = "Non-destructive astronomical image processing",
        ["Help.About.Body"] = "StarSim Core processes already stacked planetary, lunar and solar TIFF/PNG images. Beginner and Expert are two views over the same canonical processing pipeline; changing mode never alters the image parameters.",
        ["Help.About.Principles"] = "Core principles",
        ["Help.About.NonDestructive"] = "• The source file and immutable master image are never overwritten.",
        ["Help.About.SharedPipeline"] = "• Beginner presets and Expert controls edit the same visible, undoable processor state.",
        ["Help.About.Float"] = "• Processing uses floating-point samples internally; clipping is deferred to display or integer export.",
        ["Help.About.Input"] = "• V1 is a post-processing application. It does not stack videos or replace capture/stacking software.",
        ["Help.About.Safety"] = "Keep the original stacked image. Export to a new TIFF/PNG or save a .starsim project; never choose the source file as the export destination.",
        ["Help.About.Support.Title"] = "Support the Star Sim Association",
        ["Help.About.Support.Body"] = "If StarSim Core is useful to you, you can support its continued development and the astronomy activities of the Star Sim Association with a donation.",
        ["Help.About.Support.Credit"] = "StarSim Core is developed by Gîrdeanu Ștefan Victor, President of the Star Sim Association, together with an AI agent.",
        ["Help.About.Support.Button"] = "Open https://starsim.ro/",
        ["Help.About.Support.LogoTip"] = "Star Sim Association logo",
        ["Help.Beginner.Title"] = "A reliable Beginner workflow",
        ["Help.Beginner.Intro"] = "Beginner mode gives you target-aware starting points while keeping every result editable in Expert mode.",
        ["Help.Beginner.Step1.Title"] = "1. Open an already stacked image",
        ["Help.Beginner.Step1.Body"] = "Use an 8/16-bit TIFF or PNG. The newly opened image starts at Default/Default with every processor bypassed, so Original and Processed are initially identical.",
        ["Help.Beginner.Step2.Title"] = "2. Choose the target and strength profile",
        ["Help.Beginner.Step2.Body"] = "Select Jupiter, Saturn, Mars, Venus, Moon, Solar or Generic, then Natural, Balanced, Detailed or Strong. Selection only stages the visible recipe; it does not process until you press Apply Preset.",
        ["Help.Beginner.Step3.Title"] = "3. Apply, inspect at 100%, compare",
        ["Help.Beginner.Step3.Body"] = "Press Apply Preset, enable Before/After and inspect fine edges at 100%. Balanced is the recommended first attempt. Strong is intended only for clean, well-sampled data.",
        ["Help.Beginner.Step4.Title"] = "4. Adjust one control at a time",
        ["Help.Beginner.Step4.Body"] = "Detail controls only Wavelet L1–L6 gains; Noise Reduction controls only the dedicated denoiser; Brightness, Contrast and Color own their respective tone/color processors. Undo returns to the previous committed state.",
        ["Help.Beginner.Step5.Title"] = "5. Save the state or export",
        ["Help.Beginner.Step5.Body"] = "Save a .starsim project to preserve source reference, workflow and parameters. Export produces a new full-resolution image. Switching to Expert preserves the exact same pipeline state.",
        ["Help.Beginner.Tip"] = "Practical rule: stop increasing Detail when grain, double edges or bright/dark halos become easier to see than real planetary structure.",
        ["Help.Expert.Title"] = "Expert pipeline and module guide",
        ["Help.Expert.Intro"] = "Expert mode exposes every processor, bypass switch and canonical parameter. Use the duplicate-panel button to detach a movable module window. Editing a parameter activates its compatible module automatically.",
        ["Help.Expert.Warning"] = "Do not stack several sharpening modules at high strength. Prefer one primary detail method, then add only a small complementary correction if the image genuinely benefits.",
        ["Help.Expert.PipelineOrder"] = "Production order — earlier modules feed every module below them:",
        ["Help.Module.RgbAlign.Usage"] = "Run before restoration/sharpening when red or blue fringes are visible. Try Auto first; use manual offsets only for a small residual mismatch.",
        ["Help.Module.NoiseReduction.Usage"] = "Use modestly before sharpening. Luminance targets brightness grain, Chrominance targets color speckles, and Fine Detail Protection prevents useful small structures from being smoothed away.",
        ["Help.Module.RichardsonLucy.Usage"] = "Use on genuinely blurred, well-sampled data. Start with few iterations, low Strength and a PSF radius matching the blur. Stop when ringing or granular artifacts appear.",
        ["Help.Module.Wavelet.Usage"] = "The main planetary detail tool. L1 affects the finest useful structures; L2–L3 progressively larger detail; L4–L6 broad structure. A Classic gain of 1 is neutral. Advanced Denoise, Threshold and widths remain independent.",
        ["Help.Module.UnsharpMask.Usage"] = "A classic edge enhancer. Radius chooses the structure size, Amount the strength and Threshold protects small differences/noise. Keep it low when Wavelet sharpening is already strong.",
        ["Help.Module.MultiScaleSharpen.Usage"] = "Balances a fine and a broad detail band. Use it instead of, or very lightly after, another sharpener; excessive broad Amount creates unnatural local contrast.",
        ["Help.Module.Deringing.Usage"] = "Use after sharpening to reduce bright/dark edge oscillations and planetary-limb halos. It repairs artifacts; it is not a detail enhancer.",
        ["Help.Module.LocalDetail.Usage"] = "Raises local and micro contrast in medium structures. Useful for belts, clouds and lunar relief, but excessive values make backgrounds mottled and limbs harsh.",
        ["Help.Module.AdvancedColor.Usage"] = "Correct white balance, temperature and tint before pushing saturation. Vibrance favors weaker colors and is usually safer than large global saturation changes.",
        ["Help.Module.RgbBalance.Usage"] = "Adjust red, green and blue gains to remove a color cast. Use Auto RGB Balance as a conservative starting point, then verify neutral areas and the histogram.",
        ["Help.Module.Saturation.Usage"] = "Controls global color intensity. Increase only after channel balance is credible; strong saturation also amplifies chromatic noise and edge color artifacts.",
        ["Help.Module.AdvancedTone.Usage"] = "Sets black/white points and independently shapes shadows and highlights. Watch the histogram and preserve useful data at both ends.",
        ["Help.Module.Exposure.Usage"] = "Moves linear brightness in photographic stops. Use for overall level, not as a substitute for black/white-point correction.",
        ["Help.Module.Contrast.Usage"] = "Expands or compresses tonal separation around the midpoint. Increase gently; high contrast can hide low-contrast planetary detail and clip apparent transitions.",
        ["Help.Module.Gamma.Usage"] = "Shapes midtones while preserving endpoints. Values below/above neutral redistribute midtone brightness; use after exposure and before judging final contrast.",
        ["Help.Plugins.Title"] = "Native processing plugins",
        ["Help.Plugins.Body"] = "A plugin is a Windows x64 DLL that contributes one or more float32 image processors. StarSim Core reads its metadata and parameter schema, then generates Expert sliders, reset behavior and a detachable panel automatically.",
        ["Help.Plugins.Install.Title"] = "Install and activate",
        ["Help.Plugins.Install.Body"] = "Open Plugins → Plugin Manager → Install plugin, choose the DLL, enable external plugins and restart. Accepted processors appear in Expert mode under PLUGINS.",
        ["Help.Plugins.Panel.Title"] = "Where the panel appears",
        ["Help.Plugins.Panel.Body"] = "Plugin processors are appended after built-in Tone stages. Their enabled state and parameters participate in preview, Undo/Redo, projects, custom presets and export.",
        ["Help.Plugins.Develop.Title"] = "Develop a plugin",
        ["Help.Plugins.Develop.Body"] = "Open Plugins → Plugin Developer Guide or the sdk folder included in the release. It contains the ABI header, standalone CMake project, complete README and an RGB-to-B&W / Invert & Tint example.",
        ["Help.Plugins.Security"] = "Native plugins execute inside the StarSim Core process and are not sandboxed. Install only DLLs you trust and keep all dependency DLLs beside the plugin.",
        ["Help.Footer"] = "Ctrl+F1 opens this guide. All controls and module descriptions follow the selected application language.",

        // Built-in parameter labels
        ["Parameter.auto"] = "Auto alignment",
        ["Parameter.redX"] = "Red X",
        ["Parameter.redY"] = "Red Y",
        ["Parameter.greenX"] = "Green X",
        ["Parameter.greenY"] = "Green Y",
        ["Parameter.blueX"] = "Blue X",
        ["Parameter.blueY"] = "Blue Y",
        ["Parameter.search"] = "Search radius",
        ["Parameter.luminance"] = "Luminance",
        ["Parameter.chrominance"] = "Chrominance",
        ["Parameter.detailProtection"] = "Fine detail protection",
        ["Parameter.threshold"] = "Threshold",
        ["Parameter.iterations"] = "Iterations",
        ["Parameter.psfRadius"] = "PSF radius",
        ["Parameter.strength"] = "Strength",
        ["Parameter.damping"] = "Damping",
        ["Parameter.amount"] = "Amount",
        ["Parameter.radius"] = "Radius",
        ["Parameter.fineAmount"] = "Fine amount",
        ["Parameter.fineRadius"] = "Fine radius",
        ["Parameter.broadAmount"] = "Broad amount",
        ["Parameter.broadRadius"] = "Broad radius",
        ["Parameter.edgeProtection"] = "Edge protection",
        ["Parameter.localAmount"] = "Local contrast",
        ["Parameter.localRadius"] = "Local radius",
        ["Parameter.microAmount"] = "Microcontrast",
        ["Parameter.microRadius"] = "Micro radius",
        ["Parameter.whiteRed"] = "White balance R",
        ["Parameter.whiteGreen"] = "White balance G",
        ["Parameter.whiteBlue"] = "White balance B",
        ["Parameter.temperature"] = "Temperature",
        ["Parameter.tint"] = "Tint",
        ["Parameter.vibrance"] = "Vibrance",
        ["Parameter.red"] = "Red",
        ["Parameter.green"] = "Green",
        ["Parameter.blue"] = "Blue",
        ["Parameter.brightness"] = "Brightness",
        ["Parameter.blackPoint"] = "Black point",
        ["Parameter.whitePoint"] = "White point",
        ["Parameter.highlights"] = "Highlights",
        ["Parameter.shadows"] = "Shadows",
        ["Parameter.stops"] = "Exposure",
        ["Parameter.factor"] = "Contrast",
        ["Parameter.gamma"] = "Gamma",
        ["Parameter.core.saturation.amount"] = "Saturation",
        ["Parameter.globalStrength"] = "Global strength",
        ["Parameter.initialLayerWidth"] = "Initial Gaussian width",
        ["Parameter.linked"] = "Linked wavelets",
        ["Parameter.ultraFineLayerEnhancementFactor"] = "Layer 1 gain",
        ["Parameter.fineLayerEnhancementFactor"] = "Layer 2 gain",
        ["Parameter.smallLayerEnhancementFactor"] = "Layer 3 gain",
        ["Parameter.mediumLayerEnhancementFactor"] = "Layer 4 gain",
        ["Parameter.largeLayerEnhancementFactor"] = "Layer 5 gain",
        ["Parameter.structureLayerEnhancementFactor"] = "Layer 6 gain",
        ["Parameter.ultraFineLayerGaussianWidth"] = "Layer 1 Gaussian width",
        ["Parameter.fineLayerGaussianWidth"] = "Layer 2 Gaussian width",
        ["Parameter.smallLayerGaussianWidth"] = "Layer 3 Gaussian width",
        ["Parameter.mediumLayerGaussianWidth"] = "Layer 4 Gaussian width",
        ["Parameter.largeLayerGaussianWidth"] = "Layer 5 Gaussian width",
        ["Parameter.structureLayerGaussianWidth"] = "Layer 6 Gaussian width",
        ["Parameter.ultraFineGaussianWidth"] = "Layer 1 Gaussian width",
        ["Parameter.fineGaussianWidth"] = "Layer 2 Gaussian width",
        ["Parameter.smallGaussianWidth"] = "Layer 3 Gaussian width",
        ["Parameter.mediumGaussianWidth"] = "Layer 4 Gaussian width",
        ["Parameter.largeGaussianWidth"] = "Layer 5 Gaussian width",
        ["Parameter.structureGaussianWidth"] = "Layer 6 Gaussian width",
        ["Parameter.ultraFineLayerDenoise"] = "Layer 1 denoise",
        ["Parameter.fineLayerDenoise"] = "Layer 2 denoise",
        ["Parameter.smallLayerDenoise"] = "Layer 3 denoise",
        ["Parameter.mediumLayerDenoise"] = "Layer 4 denoise",
        ["Parameter.largeLayerDenoise"] = "Layer 5 denoise",
        ["Parameter.structureLayerDenoise"] = "Layer 6 denoise",
        ["Parameter.ultraFineDenoise"] = "Layer 1 denoise",
        ["Parameter.fineDenoise"] = "Layer 2 denoise",
        ["Parameter.smallDenoise"] = "Layer 3 denoise",
        ["Parameter.mediumDenoise"] = "Layer 4 denoise",
        ["Parameter.largeDenoise"] = "Layer 5 denoise",
        ["Parameter.structureDenoise"] = "Layer 6 denoise",
        ["Parameter.ultraFineLayerThreshold"] = "Layer 1 threshold",
        ["Parameter.fineLayerThreshold"] = "Layer 2 threshold",
        ["Parameter.smallLayerThreshold"] = "Layer 3 threshold",
        ["Parameter.mediumLayerThreshold"] = "Layer 4 threshold",
        ["Parameter.largeLayerThreshold"] = "Layer 5 threshold",
        ["Parameter.structureLayerThreshold"] = "Layer 6 threshold",
        ["Parameter.ultraFineThreshold"] = "Layer 1 threshold",
        ["Parameter.fineThreshold"] = "Layer 2 threshold",
        ["Parameter.smallThreshold"] = "Layer 3 threshold",
        ["Parameter.mediumThreshold"] = "Layer 4 threshold",
        ["Parameter.largeThreshold"] = "Layer 5 threshold",
        ["Parameter.structureThreshold"] = "Layer 6 threshold",
        ["Parameter.soloLayer"] = "Solo layer",
        ["Parameter.scaleScheme"] = "Scale scheme",
        ["Parameter.stepIncrement"] = "Linear step increment",
        ["Parameter.backend"] = "Decomposition backend",
        ["Parameter.decompositionBackend"] = "Decomposition backend",
    };

    public static IReadOnlyDictionary<string, string> RomanianCatalog { get; } = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        // App & Toolbar
        ["App.Title"] = "StarSim Core",
        ["App.Subtitle"] = "IMAGISTICĂ ASTROFOTOGRAFICĂ",
        ["Toolbar.OpenImage"] = "▣  Deschide imagine",
        ["Toolbar.OpenImage.Tip"] = "Deschideți un fișier TIFF sau PNG pe 8/16 biți fără modificări.",
        ["Toolbar.OpenProject"] = "⎘  Deschide proiect",
        ["Toolbar.OpenProject.Tip"] = "Deschideți un fișier de proiect .starsim.",
        ["Toolbar.SaveProject"] = "💾  Salvează proiect",
        ["Toolbar.SaveProject.Tip"] = "Salvați starea curentă într-un fișier de proiect .starsim.",
        ["Toolbar.Undo.Tip"] = "Anulează ultima comandă de parametri.",
        ["Toolbar.Redo.Tip"] = "Refă ultima comandă de parametri.",
        ["Toolbar.BeforeAfter"] = "◧  Înainte / După",
        ["Toolbar.BeforeAfter.Tip"] = "Trageți separatorul vertical pentru a compara originalul cu imaginea procesată.",
        ["Toolbar.ZoomIn.Tip"] = "Mărește",
        ["Toolbar.ZoomOut.Tip"] = "Micșorează",
        ["Toolbar.Fit"] = "⛶  Potrivește",
        ["Toolbar.Fit.Tip"] = "Potrivește imaginea în vizualizator",
        ["Toolbar.Export"] = "⇧  Exportă…",
        ["Toolbar.Export.Tip"] = "Exportați imaginea la rezoluție completă în TIFF 16 biți sau PNG 8/16 biți.",
        ["Toolbar.Performance"] = "⚙  Performanță",
        ["Toolbar.Performance.Tip"] = "Limite CPU, memorie și previzualizare interactivă",

        // Menu Bar
        ["Menu.File"] = "_Fișier",
        ["Menu.File.OpenImage"] = "_Deschide imagine…",
        ["Menu.File.OpenProject"] = "Deschide _proiect…",
        ["Menu.File.SaveProject"] = "_Salvează proiect",
        ["Menu.File.SaveProjectAs"] = "Salvează proiect _ca…",
        ["Menu.File.Export"] = "_Exportă imagine…",
        ["Menu.File.Exit"] = "_Ieșire",
        ["Menu.Edit"] = "_Editare",
        ["Menu.Edit.Undo"] = "_Anulează",
        ["Menu.Edit.Redo"] = "_Refă",
        ["Menu.Edit.ResetAll"] = "Resetează _toate modulele",
        ["Menu.View"] = "_Vizualizare",
        ["Menu.View.Fit"] = "_Potrivește în vizualizator",
        ["Menu.View.ZoomIn"] = "_Mărește",
        ["Menu.View.ZoomOut"] = "M_icșorează",
        ["Menu.View.BeforeAfter"] = "Comparație Înainte / _După",
        ["Menu.View.Beginner"] = "Modul Î_ncepător",
        ["Menu.View.Expert"] = "Modul E_xpert",
        ["Menu.Process"] = "_Procesare",
        ["Menu.Presets"] = "P_reseturi",
        ["Menu.Settings"] = "_Setări",
        ["Menu.Settings.Language"] = "Limbă / Language",
        ["Menu.Settings.Performance"] = "_Performanță & Limite Hardware…",
        ["Menu.Help"] = "_Ajutor",
        ["Menu.Help.Guide"] = "_Ghid de utilizare…",
        ["Menu.Help.About"] = "_Despre StarSim Core…",

        // Modes
        ["Mode.Beginner"] = "Începător",
        ["Mode.Expert"] = "Expert",

        // Viewer
        ["Viewer.Title"] = "VIZUALIZATOR",
        ["Viewer.SourcePreview"] = "Previzualizare sursă",
        ["Viewer.Fit"] = "POTRIVEȘTE",
        ["Viewer.NoImage"] = "Nicio imagine încărcată",
        ["Viewer.NoImageHint"] = "Deschideți un fișier TIFF sau PNG deja suprapus pentru a începe",
        ["Viewer.Original"] = "ORIGINAL",
        ["Viewer.Processed"] = "PROCESAT",

        // Categories
        ["Category.Alignment"] = "Aliniere",
        ["Category.Restoration"] = "Restaurare",
        ["Category.Detail"] = "Detalii",
        ["Category.AdvancedSharpening"] = "Claritate avansată",
        ["Category.Color"] = "Culoare",
        ["Category.Tone"] = "Ton",

        // Wavelets V2
        ["Wavelets.Title"] = "Detalii multi-scală Wavelet",
        ["Wavelets.Mode.Classic"] = "Clasic",
        ["Wavelets.Mode.Advanced"] = "Avansat",
        ["Wavelets.GlobalStrength"] = "Intensitate globală",
        ["Wavelets.InitialWidth"] = "Lățime inițială",
        ["Wavelets.Linked"] = "Wavelet-uri legate",
        ["Wavelets.ResetAll"] = "Resetează Wavelet",
        ["Wavelets.ResetLayer"] = "Resetează",
        ["Wavelets.Solo"] = "Solo",
        ["Wavelets.Info.Title"] = "Ce sunt wavelet-urile?",
        ["Wavelets.Info.Body"] = "Wavelet-urile descompun recursiv imaginea planetară în 6 scale Gaussiene. Sliderele 1-6 controlează direct benzi de detaliu progresiv mai largi; lățimea, reducerea zgomotului și pragul rămân controale Advanced independente.",
        ["Wavelets.Layer1.Name"] = "Stratul 1 — Detalii ultrafine",
        ["Wavelets.Layer1.Help"] = "Accentuează cele mai mici structuri vizibile. Util pentru texturi planetare fine. Valorile mari pot amplifica zgomotul sau efectul de ringing.",
        ["Wavelets.Layer2.Name"] = "Stratul 2 — Detalii fine",
        ["Wavelets.Layer2.Help"] = "Accentuează detaliile fine de suprafață, cratere mici, festoane și granițe planetare netede.",
        ["Wavelets.Layer3.Name"] = "Stratul 3 — Detalii medii-fine",
        ["Wavelets.Layer3.Help"] = "Accentuează formațiunile planetare intermediare, sisteme de fisuri și marginile benzilor de nori.",
        ["Wavelets.Layer4.Name"] = "Stratul 4 — Detalii medii",
        ["Wavelets.Layer4.Help"] = "Accentuează centurile planetare principale, cratere mari și formațiuni de albedo proeminente.",
        ["Wavelets.Layer5.Name"] = "Stratul 5 — Structuri mari",
        ["Wavelets.Layer5.Help"] = "Accentuează contrastul regional larg, furtunile de mari dimensiuni și calotele polare.",
        ["Wavelets.Layer6.Name"] = "Stratul 6 — Structură globală",
        ["Wavelets.Layer6.Help"] = "Accentuează distribuția globală de luminozitate a discului și gradienții planetari ampli.",
        ["Wavelets.Param.EnhancementFactor"] = "Amplificare",
        ["Wavelets.Param.GaussianWidth"] = "Lățime Gaussiană",
        ["Wavelets.Param.Denoise"] = "Reducere zgomot",
        ["Wavelets.Param.Threshold"] = "Prag",

        // Modules
        ["Module.RgbAlign"] = "Aliniere RGB",
        ["Module.NoiseReduction"] = "Reducere zgomot",
        ["Module.RichardsonLucy"] = "Richardson-Lucy",
        ["Module.Deringing"] = "Reducere ringing / protecție halo",
        ["Module.Wavelet"] = "Detalii multi-scală Wavelet",
        ["Module.LocalDetail"] = "Detalii locale",
        ["Module.UnsharpMask"] = "Mască de accentuare (Unsharp Mask)",
        ["Module.MultiScaleSharpen"] = "Claritate multi-scală",
        ["Module.AdvancedColor"] = "Culoare avansată",
        ["Module.RgbBalance"] = "Echilibru canale RGB",
        ["Module.Saturation"] = "Saturație",
        ["Module.AdvancedTone"] = "Ton avansat",
        ["Module.Exposure"] = "Luminozitate / Expunere",
        ["Module.Contrast"] = "Contrast",
        ["Module.Gamma"] = "Gama",
        ["Module.RgbAlign.Description"] = "Aliniază canalele de culoare cu precizie sub-pixel",
        ["Module.NoiseReduction.Description"] = "Reduce zgomotul de luminanță și crominanță păstrând detaliile",
        ["Module.RichardsonLucy.Description"] = "Reduce neclaritatea optică prin restaurare iterativă",
        ["Module.Deringing.Description"] = "Reduce ringing-ul și protejează muchiile contrastante",
        ["Module.Wavelet.Description"] = "Accentuează direct detaliile pe șase scale spațiale",
        ["Module.LocalDetail.Description"] = "Accentuează microcontrastul și structurile medii",
        ["Module.UnsharpMask.Description"] = "Accentuează clasic muchiile în funcție de rază",
        ["Module.MultiScaleSharpen.Description"] = "Combină claritatea fină și cea pe structuri largi",
        ["Module.AdvancedColor.Description"] = "Balans de alb, temperatură, tentă și vibranță",
        ["Module.RgbBalance.Description"] = "Echilibrează câștigul canalelor roșu, verde și albastru",
        ["Module.Saturation.Description"] = "Controlează intensitatea globală a culorilor",
        ["Module.AdvancedTone.Description"] = "Modelează punctele alb/negru, umbrele și luminile",
        ["Module.Exposure.Description"] = "Reglează luminozitatea liniară în trepte de expunere",
        ["Module.Contrast.Description"] = "Extinde sau comprimă separarea tonală",
        ["Module.Gamma.Description"] = "Modelează tonurile medii fără a schimba extremitățile",

        // Warnings
        ["Warning.MultiSharpening"] = "Sunt active simultan multiple motoare de accentuare a detaliilor (Wavelet + Claritate/RL). Acest lucru poate amplifica artefactele de ringing sau supra-accentuarea.",

        // Processing & Errors
        ["Processing.InProgress"] = "Se procesează…",
        ["Processing.Complete"] = "Finalizat",
        ["Processing.Cancelled"] = "Anulat",
        ["Processing.OpeningImage"] = "Se deschide imaginea…",
        ["Processing.Cancel"] = "Anulează",
        ["Processing.LatestPreviewVisible"] = "Cea mai recentă previzualizare validă rămâne vizibilă în timpul procesării.",
        ["Error.ProcessingFailed"] = "Eroare de procesare",
        ["Error.TechnicalDetails"] = "Detalii tehnice",
        ["Error.CopyDetails"] = "Copiază detaliile",
        ["Error.OpenLogFolder"] = "Deschide dosarul de jurnale",
        ["Error.NativeOperationFailed"] = "Operațiunea nativă a eșuat",

        // Beginner Mode
        ["Beginner.Title"] = "Modul Începător",
        ["Beginner.Subtitle"] = "Controale simple. Stare matematică comună.",
        ["Beginner.Target"] = "ȚINTĂ",
        ["Beginner.TargetQuestion"] = "Ce ați fotografiat?",
        ["Beginner.Preset"] = "PRESET",
        ["Beginner.PresetQuestion"] = "Alegeți un punct de pornire",
        ["Beginner.ApplyPreset"] = "Aplică presetul",
        ["Beginner.Adjustments"] = "AJUSTĂRI",
        ["Beginner.PresetStrength"] = "Intensitate preset",
        ["Beginner.Detail"] = "Detaliu",
        ["Beginner.NoiseReduction"] = "Reducere zgomot",
        ["Beginner.Color"] = "Culoare",
        ["Beginner.Brightness"] = "Luminozitate",
        ["Beginner.Contrast"] = "Contrast",
        ["Beginner.ColorPreset"] = "PRESET CULOARE",
        ["Beginner.AutoRgbBalance"] = "Auto echilibrare RGB",

        // Expert Mode
        ["Expert.Histogram"] = "Histogramă",
        ["Expert.ProcessModules"] = "MODULE DE PROCESARE",
        ["Expert.ModuleHint"] = "Faceți clic pe modul pentru a-l regla în fereastra de precizie",
        ["Expert.ResetAll"] = "Resetează tot",
        ["Expert.ResetCategory"] = "Resetează categoria",
        ["Expert.ResetModule"] = "Resetează",
        ["Expert.Configure"] = "⚙ Configurează…",
        ["Expert.Parameters"] = "{0} parametri",
        ["Expert.EnabledCount"] = "{0}/{1} active",

        // Precision Tool Window
        ["ToolWindow.Enabled"] = "Activat",
        ["ToolWindow.ResetModule"] = "Resetează modulul",
        ["ToolWindow.PrecisionHint"] = "Ajustați parametrii cu precizie milimetrică. Modificările se actualizează în timp real.",
        ["ToolWindow.Close"] = "Închide",

        // Targets
        ["Target.Jupiter"] = "Jupiter",
        ["Target.Saturn"] = "Saturn",
        ["Target.Mars"] = "Marte",
        ["Target.Venus"] = "Venus",
        ["Target.Moon"] = "Luna",
        ["Target.Solar"] = "Soare",
        ["Target.Generic"] = "Generic",

        // Presets
        ["Preset.Natural"] = "Natural",
        ["Preset.Balanced"] = "Echilibrat",
        ["Preset.Detailed"] = "Detaliat",
        ["Preset.Strong"] = "Pronunțat",

        // Color Presets
        ["ColorPreset.Natural"] = "Natural",
        ["ColorPreset.Neutral"] = "Neutru",
        ["ColorPreset.Warm"] = "Cald",
        ["ColorPreset.Vivid"] = "Vivid",

        // Performance Profiles
        ["Performance.Profile.Balanced"] = "Echilibrat",
        ["Performance.Profile.HighThroughput"] = "Randament ridicat",
        ["Performance.Profile.LowMemory"] = "Memorie redusă",
        ["Performance.Profile.PowerSaver"] = "Economisire energie",

        // Settings Dialog
        ["Settings.Title"] = "Performanță & Limite Hardware",
        ["Settings.Language"] = "Limbă",

        // Interfața completă a aplicației
        ["Menu.View.FullScreen"] = "_Ecran complet",
        ["Menu.Process.Wavelet"] = "Detalii multi-scală Wavelet…",
        ["Menu.Process.RichardsonLucy"] = "Deconvoluție Richardson-Lucy…",
        ["Menu.Process.NoiseReduction"] = "Reducere zgomot…",
        ["Menu.Process.LocalDetail"] = "Contrast și detalii locale…",
        ["Menu.Process.UnsharpMask"] = "Mască de accentuare…",
        ["Menu.Process.MultiScaleSharpen"] = "Claritate multi-scală…",
        ["Menu.Process.Deringing"] = "Reducere ringing / protecție halo…",
        ["Menu.Process.RgbAlign"] = "Aliniere canale RGB…",
        ["Menu.Process.AdvancedColor"] = "Culoare și balans avansat…",
        ["Menu.Process.RgbBalance"] = "Echilibru RGB…",
        ["Menu.Process.Saturation"] = "Saturație…",
        ["Menu.Process.AdvancedTone"] = "Ton și curbe avansate…",
        ["Menu.Process.Exposure"] = "Luminozitate / Expunere…",
        ["Menu.Process.Contrast"] = "Contrast…",
        ["Menu.Process.Gamma"] = "Gama…",
        ["Menu.Presets.SaveCustom"] = "Salvează preset personalizat…",
        ["Menu.Plugins"] = "Pl_uginuri",
        ["Menu.Plugins.Manager"] = "_Manager pluginuri…",
        ["Menu.Plugins.Install"] = "_Instalează plugin…",
        ["Menu.Plugins.DeveloperGuide"] = "_Ghid pentru dezvoltarea pluginurilor…",
        ["Toolbar.OpenShort"] = "▱  Deschide",
        ["Toolbar.SaveShort"] = "▣  Salvează",
        ["Toolbar.Undo"] = "↶  Anulează",
        ["Toolbar.Redo"] = "↷  Refă",
        ["Toolbar.Compare"] = "◧  Compară",
        ["Toolbar.Compare.Tip"] = "Afișează sau ascunde separatorul mobil înainte/după",
        ["Viewer.ImageViewer"] = "Vizualizator imagine",
        ["Viewer.FullScreen.Tip"] = "Ecran complet",
        ["Viewer.PixelHint"] = "Deplasați cursorul pe imagine pentru a inspecta pixelii",
        ["Viewer.OutsideImage"] = "În afara imaginii",
        ["Viewer.Gray"] = "Gri",
        ["Viewer.ZoomLabel"] = "Zoom:",
        ["Histogram.NoData"] = "FĂRĂ DATE DE IMAGINE",
        ["Histogram.LiveDescription"] = "Distribuția RGB în timp real a imaginii procesate curente",
        ["Histogram.OpenImageHint"] = "Deschideți o imagine pentru a genera histograma.",
        ["Histogram.Title"] = "StarSim Core — Histogramă",
        ["Histogram.OpenSeparate.Tip"] = "Deschide histograma într-o fereastră separată",
        ["Panel.Processing"] = "Procesare",
        ["Panel.SearchModules"] = "Caută module…",
        ["Panel.BeginnerWorkflow"] = "FLUX ÎNCEPĂTOR",
        ["Panel.ModuleCount"] = "{0} module",
        ["Panel.OpenSeparate.Tip"] = "Deschide acest modul într-un panou separat",
        ["Panel.OpenSeparate"] = "Deschide panou separat  ⧉",
        ["Panel.AdvancedDiagnostic"] = "Avansat / Diagnostic…  ⧉",
        ["Group.DETAIL"] = "DETALII",
        ["Group.COLOR"] = "CULOARE",
        ["Group.TONE"] = "TON",
        ["Group.PLUGINS"] = "PLUGINURI",

        // Acțiuni și dialoguri comune
        ["Common.Close"] = "Închide",
        ["Common.Cancel"] = "Anulează",
        ["Common.Automatic"] = "Automat",
        ["Common.Auto"] = "Automat",
        ["Common.Manual"] = "Manual",
        ["Common.Refresh"] = "Reîmprospătează",
        ["Dialog.RelocateSource.Title"] = "Relocare imagine sursă",
        ["Dialog.RelocateSource.Locate"] = "Localizează fișierul sursă…",
        ["Dialog.CustomPreset.Title"] = "Salvează preset personalizat",
        ["Dialog.CustomPreset.Name"] = "Numele presetului",
        ["Dialog.CustomPreset.Description"] = "Descriere",
        ["Dialog.CustomPreset.Save"] = "Salvează presetul",
        ["FilePicker.OpenImage"] = "Deschide imagine suprapusă",
        ["FilePicker.Images"] = "Imagini TIFF și PNG",
        ["FilePicker.OpenProject"] = "Deschide proiect StarSim",
        ["FilePicker.SaveProject"] = "Salvează proiect StarSim",
        ["FilePicker.Projects"] = "Proiecte StarSim (*.starsim)",
        ["FilePicker.ExportImage"] = "Exportă imaginea procesată",
        ["FilePicker.Tiff16"] = "Imagine TIFF pe 16 biți (*.tif, *.tiff)",
        ["FilePicker.Png"] = "Imagine PNG (*.png)",
        ["FilePicker.LocateSource"] = "Localizează imaginea sursă lipsă",
        ["FilePicker.InstallPlugin"] = "Instalează plugin nativ StarSim Core",
        ["FilePicker.PluginDll"] = "DLL plugin nativ (*.dll)",
        ["FilePicker.ExportWavelet"] = "Exportă diagnosticele de calibrare Wavelet",

        // Valori de flux și rezumate
        ["Target.Default"] = "Implicit",
        ["Preset.Default"] = "Implicit",
        ["ColorPreset.Default"] = "Implicit",
        ["Beginner.CustomModified"] = "Personalizat/Modificat",
        ["Beginner.NeutralDescription"] = "Stare de procesare neutră. Alegeți explicit o țintă și un preset pentru a aplica o rețetă.",
        ["Beginner.PresetDescription"] = "Punct de pornire tehnic conservator {0} pentru datele selectate de tip {1}; destinat calibrării ulterioare, nu reprezintă un optim științific universal.",
        ["Beginner.PresetDescription.Natural"] = "Punct de pornire delicat pentru {0}: detaliu și reducere de zgomot moderate. Apasă Aplică presetul, apoi ajustează câte un control.",
        ["Beginner.PresetDescription.Balanced"] = "Punct de pornire recomandat pentru {0}: detaliu fin util, cu zgomot și structuri largi controlate. Apasă Aplică presetul pentru previzualizare.",
        ["Beginner.PresetDescription.Detailed"] = "Detalii fine și medii mai puternice pentru date {0} bune. Urmărește granulația și contururile luminoase; redu Detaliu dacă este necesar.",
        ["Beginner.PresetDescription.Strong"] = "Detaliu agresiv pentru date {0} foarte curate și bine eșantionate. Verifică imaginea la 100% și redu dacă apar zgomot sau halouri.",
        ["Mode.BeginnerWorkspace"] = "Flux Începător",
        ["Mode.ExpertWorkspace"] = "Spațiu de lucru Expert",
        ["Summary.SourceNone"] = "Sursă: niciuna",
        ["Summary.Source"] = "{0}  •  {1}×{2}  •  {3} biți {4}",
        ["Summary.NoImage"] = "Nicio imagine  •  POTRIVIT  •  float32",
        ["Summary.Image"] = "{0}×{1}  •  {2} canal(e)  •  float32",
        ["Summary.AlphaIgnored"] = "Canal alfa detectat și ignorat",
        ["Summary.SourceImmutable"] = "Pixelii sursă rămân nemodificați",
        ["Summary.NoHistogram"] = "Nu există date pentru histogramă",
        ["Summary.Histogram"] = "Min {0:0.000}   |   Medie {1:0.000}   |   Max {2:0.000}",
        ["Performance.Resolved"] = "{0}: {1}",
        ["Performance.Diagnostics"] = "Procesoare logice {0} • fire de lucru {1} • RAM disponibil {2:0.0} GB • buget {3:0.0} GB • urmărit {4:0} MB • pool {5:0} MB ({6} buffere, {7} reutilizări/{8} alocări) • sarcini {9}",

        // Fereastra de performanță
        ["Performance.Title"] = "StarSim Core — Performanță",
        ["Performance.Header"] = "Performanță",
        ["Performance.Subtitle"] = "Politica CPU, memorie și previzualizare interactivă",
        ["Performance.Profile"] = "Profil de performanță",
        ["Performance.Profile.Help"] = "Selectați echilibrul dintre viteza procesării și răspunsul interfeței.",
        ["Performance.CpuThreads"] = "Fire CPU",
        ["Performance.MemoryLimit"] = "Limită de memorie",
        ["Performance.InteractivePreview"] = "Previzualizare interactivă",
        ["Performance.PrioritizeUi"] = "Prioritizează răspunsul interfeței",
        ["Performance.ReduceBattery"] = "Reduce utilizarea CPU pe baterie",
        ["Performance.Immediate"] = "Modificările se aplică imediat.",
        ["Performance.Preview.Auto"] = "Automat",
        ["Performance.Preview.Full"] = "Rezoluție completă",
        ["Performance.Preview.Half"] = "Jumătate de rezoluție",
        ["Performance.Preview.Quarter"] = "Sfert de rezoluție",
        ["Performance.Profile.Eco"] = "Economic",
        ["Performance.Profile.Maximum"] = "Maxim",

        // Panouri de precizie și diagnostic Wavelet
        ["ToolWindow.Parameters"] = "PARAMETRI",
        ["ToolWindow.PluginWarning"] = "PLUGIN NATIV EXTERN — FĂRĂ IZOLARE",
        ["ToolWindow.PluginProvider"] = "Plugin extern: {0} {1} • {2}",
        ["ToolWindow.PluginHint"] = "Acest procesor este furnizat de un plugin nativ care rulează în procesul aplicației și nu este izolat. Modificarea unui control îl activează și actualizează vizualizatorul.",
        ["ToolWindow.NoiseHint"] = "Măriți Luminanță sau Crominanță peste zero pentru reducerea zgomotului. Modificarea unui control activează automat modulul.",
        ["ToolWindow.GenericHint"] = "Modificarea unui control activează automat modulul și actualizează vizualizatorul în timp real.",
        ["ToolWindow.PluginFallbackDescription"] = "Procesor extern furnizat de {0}.",
        ["Wavelets.ToolTitle"] = "StarSim Core — Detalii multi-scală Wavelet",
        ["Wavelets.ResetAll.Tip"] = "Resetează toate straturile Wavelet la valorile neutre",
        ["Wavelets.Linked.Tip"] = "Leagă toate sliderele straturilor",
        ["Wavelets.Solo.Tip"] = "Previzualizare solo: izolează contribuția acestei scale",
        ["Wavelets.ResetLayer.Tip"] = "Resetează acest strat la valoarea neutră (1,0)",
        ["Wavelets.NudgeDown.Tip"] = "Scade fin (-1)",
        ["Wavelets.NudgeUp.Tip"] = "Crește fin (+1)",
        ["Wavelets.Diagnostic.Title"] = "Descompunere și diagnostic Wavelet",
        ["Wavelets.Diagnostic.Backend"] = "Motor",
        ["Wavelets.Diagnostic.ScaleScheme"] = "Schema scalelor",
        ["Wavelets.Diagnostic.LinearStep"] = "Pas liniar",
        ["Wavelets.Diagnostic.Export"] = "Exportă diagnosticele…",
        ["Wavelets.Diagnostic.InitialStatus"] = "Exportă sursa, D1–D6, L6, reconstrucția și preseturile deterministe de calibrare.",
        ["Wavelets.Diagnostic.Exporting"] = "Se exportă diagnosticele Wavelet…",
        ["Wavelets.Diagnostic.Exported"] = "Diagnostice exportate în {0}",
        ["Wavelets.Diagnostic.Failed"] = "Exportul diagnosticelor a eșuat: {0}",
        ["Wavelets.Scale.Linear"] = "Scale liniare",
        ["Wavelets.Scale.Dyadic"] = "Scale diadice (2^n)",
        ["Wavelets.Backend.RecursiveGaussian"] = "Gaussian recursiv",
        ["Wavelets.Backend.AtrousB3Spline"] = "À-trous B3 spline",
        ["Wavelets.Encoding.Float32"] = "TIFF float 32 biți",
        ["Wavelets.Encoding.UInt16"] = "TIFF 16 biți",
        ["Wavelets.Compact.Strength"] = "Intensitate",
        ["Wavelets.Compact.Layer1"] = "S1 · Ultrafin",
        ["Wavelets.Compact.Layer2"] = "S2 · Fin",
        ["Wavelets.Compact.Layer3"] = "S3 · Mediu-fin",
        ["Wavelets.Compact.Layer4"] = "S4 · Mediu",
        ["Wavelets.Compact.Layer5"] = "S5 · Mare",
        ["Wavelets.Compact.Layer6"] = "S6 · Structură",

        // Manager de pluginuri și ghid pentru dezvoltatori
        ["Plugin.Title"] = "StarSim Core — Manager de pluginuri",
        ["Plugin.Header"] = "Manager de pluginuri",
        ["Plugin.Subtitle"] = "Instalare, inspectare și administrare a extensiilor native de procesare",
        ["Plugin.SecurityBadge"] = "PLUGINURILE NATIVE NU SUNT IZOLATE",
        ["Plugin.Tab.Installed"] = "Pluginuri instalate",
        ["Plugin.Tab.Developer"] = "Ghid pentru dezvoltatori",
        ["Plugin.EnableStartup"] = "Activează pluginurile native externe la pornire",
        ["Plugin.ChangeRestart"] = "Modificările de instalare sau activare se aplică după repornire. Modulele integrate existente nu sunt înlocuite niciodată.",
        ["Plugin.Install"] = "Instalează plugin…",
        ["Plugin.OpenFolder"] = "Deschide folderul",
        ["Plugin.RestartBanner"] = "Este necesară repornirea — pipeline-ul curent rămâne neschimbat până la repornirea StarSim Core.",
        ["Plugin.None"] = "Nu există DLL-uri de plugin instalate",
        ["Plugin.NoneHint"] = "Instalați un DLL x64 de încredere sau copiați-l împreună cu dependențele sale în folderul de pluginuri.",
        ["Plugin.Remove"] = "Elimină / dezactivează",
        ["Plugin.OpenLogs"] = "Deschide jurnalele de diagnostic",
        ["Plugin.Guide.Title"] = "Creați un plugin de procesare StarSim Core",
        ["Plugin.Guide.Spec"] = "ABI v1 • contract C nativ • Windows x64 • imagini planare float32",
        ["Plugin.Guide.OpenSdk"] = "Deschide SDK-ul inclus",
        ["Plugin.Guide.OpenTutorial"] = "Deschide tutorialul complet",
        ["Plugin.TutorialMissing"] = "Tutorialul complet pentru pluginuri nu a fost găsit la: {0}",
        ["Plugin.Guide.Security"] = "Securitate: DLL-urile plugin rulează în procesul StarSim Core, cu aceleași permisiuni ca aplicația. Nu sunt izolate. Instalați numai cod în care aveți încredere.",
        ["Plugin.Guide.Step1.Title"] = "1. Fișiere și instrumente",
        ["Plugin.Guide.Step1.Body"] = "Folosiți un compilator C sau C++20 care generează un DLL Windows x64. Includeți starsim_core_plugin.h și exportați cele trei puncte de intrare C obligatorii. SDK-ul inclus conține antetul, sursa exemplu, șablonul CMake și documentația completă.",
        ["Plugin.Guide.Step2.Title"] = "2. Exporturi obligatorii",
        ["Plugin.Guide.Step2.Body"] = "Metadatele declară identitatea pluginului, numele/categoriile procesoarelor, compatibilitatea grayscale/RGB și fiecare parametru numeric cu valoare implicită, minimă, maximă și pas.",
        ["Plugin.Guide.Step3.Title"] = "3. Compilarea exemplului",
        ["Plugin.Guide.Step3.Body"] = "DLL-ul Release rezultat este pluginul instalabil. Păstrați orice DLL terț de care depinde lângă acesta, în folderul de pluginuri StarSim Core.",
        ["Plugin.Guide.Step4.Title"] = "4. Reguli pentru imagine și memorie",
        ["Plugin.Guide.Step4.Body"] = "Aplicația gazdă deține toate bufferele de intrare/ieșire. Pluginul citește planele de intrare și scrie planele de ieșire numai în timpul ssc_plugin_process; nu trebuie să păstreze sau să elibereze pointerii gazdei. Ieșirea V1 păstrează aceleași dimensiuni și același număr de canale. De aceea, procesoarele RGB-la-alb-negru scriu aceeași luminanță în R, G și B.",
        ["Plugin.Guide.Step5.Title"] = "5. Anulare, progres și jurnalizare",
        ["Plugin.Guide.Step5.Body"] = "Buclele lungi trebuie să verifice is_cancelled. Raportați o fracție normalizată 0–1 și un mesaj scurt UTF-8 pentru etapă. Intrările log_message sunt scrise în jurnalul de diagnostic StarSim Core. Nu propagați niciodată excepții C++ prin ABI-ul C.",
        ["Plugin.Guide.Step6.Title"] = "6. Instalarea și localizarea panoului generat",
        ["Plugin.Guide.Step6.Body"] = "Instalați DLL-ul din prima filă, activați pluginurile externe și reporniți. După validare, fiecare procesor exportat apare în modul Expert, în grupul PLUGINURI. Sliderele și panoul separat, mobil, sunt generate automat din schema parametrilor. Procesoarele plugin rulează după grupul Ton, în ordinea declarată la descoperire.",
        ["Plugin.Guide.SampleTitle"] = "Exemplu de diagnostic inclus",
        ["Plugin.Guide.SampleBody"] = "starsim_diagnostic_plugin.dll exportă Invert & Tint și RGB to B&W Mix. Parametrul B&W Strength demonstrează un slider de plugin generat automat și integrarea completă în pipeline/export.",
        ["Plugin.Footer"] = "Pluginurile instalate de utilizator sunt păstrate separat de modulele integrate StarSim Core.",
        ["Plugin.Runtime.Active"] = "Runtime activ • {0} DLL-uri plugin, {1} procesoare, {2} respingeri",
        ["Plugin.Runtime.Disabled"] = "Runtime dezactivat în această sesiune • activați mai jos și reporniți StarSim Core",
        ["Plugin.Status.Ready"] = "Pregătit.",
        ["Plugin.Status.EnabledRestart"] = "Pluginurile externe au fost activate. Reporniți StarSim Core pentru a descoperi DLL-urile instalate.",
        ["Plugin.Status.DisabledRestart"] = "Pluginurile externe vor fi dezactivate la următoarea pornire. Cele încărcate acum rămân active până la repornire.",
        ["Plugin.Processors.None"] = "Niciun procesor",
        ["Plugin.Processors"] = "Procesoare: {0}",
        ["Plugin.State.Loaded"] = "Încărcat",
        ["Plugin.State.Rejected"] = "Respins",
        ["Plugin.State.Restart"] = "Repornire necesară",
        ["Plugin.State.NotLoaded"] = "Neîncărcat",
        ["Plugin.NoProcessorsRegistered"] = "Niciun procesor înregistrat.",
        ["Plugin.RestartDetail"] = "Acest DLL a fost instalat după descoperire sau nu a făcut parte din scanarea activă. Reporniți pentru validare.",
        ["Plugin.DisabledDetail"] = "Încărcarea pluginurilor externe este dezactivată în această sesiune.",
        ["Plugin.MetadataAfter"] = "Metadatele procesoarelor devin disponibile după încărcarea reușită.",
        ["Plugin.SdkMissing"] = "Folderul SDK nu există în această versiune: {0}",
        ["Plugin.Identity.Id"] = "ID: {0}",
        ["Plugin.Identity.Author"] = "Autor: {0}",
        ["Plugin.Install.NotFound"] = "Fișierul plugin nu a fost găsit: {0}",
        ["Plugin.Install.InvalidExtension"] = "Pluginurile native StarSim Core trebuie să fie fișiere Windows .dll.",
        ["Plugin.Install.AlreadyPresent"] = "Acel DLL se află deja în folderul de pluginuri al utilizatorului StarSim Core.",
        ["Plugin.Install.Success"] = "„{0}” a fost instalat. Reporniți StarSim Core pentru validare și încărcare.",
        ["Plugin.Install.Failed"] = "Instalarea pluginului a eșuat: {0}",
        ["Plugin.Remove.Bundled"] = "Pluginurile incluse în aplicație nu pot fi eliminate de aici. Eliminați-le din pachetul aplicației sau dezactivați global pluginurile externe.",
        ["Plugin.Remove.Missing"] = "Fișierul plugin selectat nu mai există.",
        ["Plugin.Remove.Success"] = "Pluginul a fost mutat în „{0}”. Reporniți StarSim Core pentru a elimina panoul său din sesiunea curentă.",
        ["Plugin.Remove.Scheduled"] = "Pluginul este utilizat acum și va fi mutat în arhiva dezactivată la următoarea pornire. {0}",

        // Mesaje de rulare
        ["Status.Ready"] = "Pregătit",
        ["Status.ExportStarting"] = "Se pornește exportul…",
        ["Status.ExportComplete"] = "Export finalizat: {0}",
        ["Status.ExportCancelled"] = "Export anulat.",
        ["Status.ExportFailed"] = "Exportul a eșuat: {0}",
        ["Export.Stage.Preparing"] = "Se pregătește pipeline-ul la rezoluție completă…",
        ["Export.Stage.ProcessingModule"] = "Se procesează {0}…",
        ["Export.Stage.Encoding"] = "Se codifică și se scrie pe disc…",
        ["Export.Stage.Writing"] = "Se scrie fișierul exportat… ({0}/{1})",
        ["Export.Stage.Complete"] = "Export finalizat.",
        ["Status.WaveletExported"] = "Diagnostice Wavelet exportate: {0}",
        ["Status.ProjectSaved"] = "Proiect salvat: {0}",
        ["Status.CustomPresetSaved"] = "Presetul personalizat „{0}” a fost salvat.",
        ["Status.FastPreview"] = "Previzualizare rapidă — {0:0.0} ms",
        ["Status.LatestPending"] = "{0} • ultima modificare este în așteptare",
        ["Status.ProcessingComplete"] = "Procesare finalizată — este afișată ultima stare",
        ["Processing.Stage.Scheduled"] = "Programat",
        ["Processing.Stage.LatestPendingUpdated"] = "Ultima sarcină în așteptare a fost actualizată",
        ["Processing.Stage.ProcessingLatestPending"] = "Se procesează ultima sarcină în așteptare",
        ["Processing.Stage.PreparingPipeline"] = "Se pregătește pipeline-ul",
        ["Processing.Stage.ComputingHistogram"] = "Se calculează histograma",
        ["Processing.Stage.PublishingPreview"] = "Se publică previzualizarea",
        ["Processing.Stage.ProcessorPipeline"] = "Pipeline de procesare",
        ["Processing.Stage.Histogram"] = "Histogramă",
        ["Processing.Stage.PublicationGate"] = "Validarea publicării",
        ["Processing.Stage.Complete"] = "Finalizat",
        ["Processing.Stage.WaveletLayer"] = "Strat Wavelet",
        ["Processing.Stage.RichardsonLucyIteration"] = "Iterație Richardson-Lucy",
        ["Processing.Stage.ProcessingModule"] = "Se procesează {0}…",
        ["Error.NativeStopped"] = "Procesarea s-a oprit neașteptat în motorul nativ.",
        ["Error.WaveletExpertOnly"] = "Modul Diagnostic Wavelet este disponibil numai în modul Expert.",
        ["Error.OpenImageForWavelet"] = "Deschideți o imagine înainte de exportul diagnosticelor Wavelet.",
        ["Error.WaveletMissing"] = "Procesorul Wavelet nu este înregistrat.",
        ["Project.SourceMissing"] = "Imaginea sursă lipsește din „{0}”. Localizați fișierul mutat.",
        ["Project.SourceMismatch"] = "Amprenta sursei din „{0}” nu corespunde. Localizați exact fișierul sursă original; imaginea diferită nu a fost asociată proiectului.",
        ["Project.SourceMismatchLocated"] = "Amprenta sursei nu corespunde. {0} Localizați exact fișierul sursă original; nicio imagine nu a fost asociată proiectului.",
        ["Project.IncompatibleSource"] = "Sursă incompatibilă: {0}",

        // Meniu contextual
        ["Context.Undo"] = "Anulează",
        ["Context.Redo"] = "Refă",
        ["Context.Fit"] = "Potrivește în vizualizator",
        ["Context.ZoomIn"] = "Mărește",
        ["Context.ZoomOut"] = "Micșorează",
        ["Context.Compare"] = "Comparație Înainte / După",
        ["Context.ResetAll"] = "Resetează toate modulele",
        ["Context.Export"] = "Exportă imaginea procesată…",

        // Ajutor și Despre
        ["Help.Title"] = "StarSim Core — Ajutor și Despre",
        ["Help.Header"] = "Ajutor StarSim Core",
        ["Help.Subtitle"] = "Flux Beginner, pipeline Expert, module și pluginuri",
        ["Help.Version"] = "Versiunea {0}",
        ["Help.Tab.About"] = "Despre",
        ["Help.Tab.Beginner"] = "Flux Beginner",
        ["Help.Tab.Expert"] = "Expert și module",
        ["Help.Tab.Plugins"] = "Pluginuri",
        ["Help.About.Title"] = "Procesare nedistructivă a imaginilor astronomice",
        ["Help.About.Body"] = "StarSim Core procesează imagini TIFF/PNG planetare, lunare și solare deja stivuite. Beginner și Expert sunt două vizualizări ale aceluiași pipeline canonic; schimbarea modului nu modifică niciodată parametrii imaginii.",
        ["Help.About.Principles"] = "Principii de bază",
        ["Help.About.NonDestructive"] = "• Fișierul sursă și imaginea master imuabilă nu sunt suprascrise niciodată.",
        ["Help.About.SharedPipeline"] = "• Preseturile Beginner și controalele Expert editează aceeași stare vizibilă și anulabilă a procesoarelor.",
        ["Help.About.Float"] = "• Procesarea utilizează intern eșantioane în virgulă mobilă; limitarea este amânată până la afișare sau export întreg.",
        ["Help.About.Input"] = "• V1 este o aplicație de post-procesare. Nu stivuiește videoclipuri și nu înlocuiește programele de captură/stivuire.",
        ["Help.About.Safety"] = "Păstrați imaginea stivuită originală. Exportați într-un TIFF/PNG nou sau salvați un proiect .starsim; nu alegeți niciodată sursa ca destinație de export.",
        ["Help.About.Support.Title"] = "Susține Asociația Star Sim",
        ["Help.About.Support.Body"] = "Dacă StarSim Core îți este util, poți susține dezvoltarea în continuare a aplicației și activitățile de astronomie ale Asociației Star Sim printr-o donație.",
        ["Help.About.Support.Credit"] = "Aplicația StarSim Core este dezvoltată de Gîrdeanu Ștefan Victor, președintele Asociației Star Sim, împreună cu un agent AI.",
        ["Help.About.Support.Button"] = "Deschide https://starsim.ro/",
        ["Help.About.Support.LogoTip"] = "Logo-ul Asociației Star Sim",
        ["Help.Beginner.Title"] = "Un flux Beginner sigur",
        ["Help.Beginner.Intro"] = "Modul Beginner oferă puncte de pornire adaptate țintei, păstrând fiecare rezultat editabil în modul Expert.",
        ["Help.Beginner.Step1.Title"] = "1. Deschideți o imagine deja stivuită",
        ["Help.Beginner.Step1.Body"] = "Utilizați un TIFF sau PNG de 8/16 biți. Imaginea nou deschisă pornește în Default/Default, cu toate procesoarele ocolite, deci Original și Procesat sunt inițial identice.",
        ["Help.Beginner.Step2.Title"] = "2. Alegeți ținta și profilul de intensitate",
        ["Help.Beginner.Step2.Body"] = "Selectați Jupiter, Saturn, Marte, Venus, Luna, Soare sau Generic, apoi Natural, Echilibrat, Detaliat ori Pronunțat. Selectarea doar pregătește rețeta vizibilă; procesarea începe când apăsați Aplică presetul.",
        ["Help.Beginner.Step3.Title"] = "3. Aplicați, verificați la 100%, comparați",
        ["Help.Beginner.Step3.Body"] = "Apăsați Aplică presetul, activați Înainte/După și verificați muchiile fine la 100%. Echilibrat este prima încercare recomandată. Pronunțat este destinat numai datelor curate și bine eșantionate.",
        ["Help.Beginner.Step4.Title"] = "4. Ajustați câte un control",
        ["Help.Beginner.Step4.Body"] = "Detaliu controlează numai gain-urile Wavelet L1–L6; Reducere zgomot controlează numai modulul dedicat; Luminozitate, Contrast și Culoare controlează procesoarele lor de ton/culoare. Anulare revine la starea confirmată anterior.",
        ["Help.Beginner.Step5.Title"] = "5. Salvați starea sau exportați",
        ["Help.Beginner.Step5.Body"] = "Salvați un proiect .starsim pentru a păstra referința sursei, fluxul și parametrii. Exportul produce o imagine nouă la rezoluție completă. Trecerea în Expert păstrează exact aceeași stare a pipeline-ului.",
        ["Help.Beginner.Tip"] = "Regulă practică: opriți creșterea Detaliului când granulația, muchiile duble sau halourile luminoase/întunecate devin mai vizibile decât structura planetară reală.",
        ["Help.Expert.Title"] = "Pipeline Expert și ghidul modulelor",
        ["Help.Expert.Intro"] = "Modul Expert expune fiecare procesor, comutator bypass și parametru canonic. Folosiți butonul de duplicare pentru a desprinde o fereastră mobilă. Editarea unui parametru activează automat modulul compatibil.",
        ["Help.Expert.Warning"] = "Nu combinați mai multe module de accentuare la intensitate mare. Alegeți o metodă principală de detaliu și adăugați doar o corecție complementară mică dacă imaginea beneficiază în mod real.",
        ["Help.Expert.PipelineOrder"] = "Ordinea de producție — modulele timpurii alimentează toate modulele de sub ele:",
        ["Help.Module.RgbAlign.Usage"] = "Rulați înainte de restaurare/accentuare când sunt vizibile franjuri roșii sau albastre. Încercați întâi Auto; folosiți deplasările manuale numai pentru nepotriviri reziduale mici.",
        ["Help.Module.NoiseReduction.Usage"] = "Folosiți moderat înainte de accentuare. Luminanță tratează granulația de luminozitate, Crominanță petele colorate, iar Protecția detaliilor fine evită netezirea structurilor utile mici.",
        ["Help.Module.RichardsonLucy.Usage"] = "Folosiți pe date realmente neclare și bine eșantionate. Porniți cu puține iterații, Intensitate mică și rază PSF apropiată de blur. Opriți când apar ringing sau artefacte granulare.",
        ["Help.Module.Wavelet.Usage"] = "Instrumentul principal pentru detaliu planetar. L1 afectează cele mai fine structuri utile; L2–L3 detalii progresiv mai mari; L4–L6 structuri largi. Gain Classic 1 este neutru. Denoise, Prag și lățimile Advanced rămân independente.",
        ["Help.Module.UnsharpMask.Usage"] = "Accentuează clasic muchiile. Raza alege dimensiunea structurii, Cantitate intensitatea, iar Prag protejează diferențele mici/zgomotul. Folosiți puțin dacă Wavelet este deja puternic.",
        ["Help.Module.MultiScaleSharpen.Usage"] = "Echilibrează o bandă fină și una largă de detaliu. Folosiți în locul altui sharpener sau foarte ușor după acesta; Cantitate largă excesivă produce contrast local artificial.",
        ["Help.Module.Deringing.Usage"] = "Folosiți după accentuare pentru a reduce oscilațiile luminoase/întunecate ale muchiilor și halourile de la limb. Repară artefacte; nu creează detaliu.",
        ["Help.Module.LocalDetail.Usage"] = "Ridică contrastul local și microcontrastul structurilor medii. Util pentru benzi, nori și relief lunar, dar valorile excesive fac fundalul pătat și limbul dur.",
        ["Help.Module.AdvancedColor.Usage"] = "Corectați balansul de alb, temperatura și tenta înainte de a crește saturația. Vibranța favorizează culorile slabe și este de obicei mai sigură decât modificările globale mari.",
        ["Help.Module.RgbBalance.Usage"] = "Reglați gain-urile roșu, verde și albastru pentru a elimina dominanta cromatică. Folosiți Balans RGB automat ca punct conservator, apoi verificați zonele neutre și histograma.",
        ["Help.Module.Saturation.Usage"] = "Controlează intensitatea globală a culorilor. Creșteți numai după un balans credibil; saturația puternică amplifică și zgomotul cromatic și artefactele colorate ale muchiilor.",
        ["Help.Module.AdvancedTone.Usage"] = "Stabilește punctele alb/negru și modelează separat umbrele și luminile. Urmăriți histograma și păstrați datele utile la ambele extremități.",
        ["Help.Module.Exposure.Usage"] = "Mută luminozitatea liniară în trepte fotografice. Folosiți pentru nivelul general, nu ca înlocuitor al corecției punctelor alb/negru.",
        ["Help.Module.Contrast.Usage"] = "Extinde sau comprimă separarea tonală în jurul punctului median. Creșteți delicat; contrastul mare poate ascunde detalii planetare slabe și tranziții utile.",
        ["Help.Module.Gamma.Usage"] = "Modelează tonurile medii păstrând extremitățile. Valorile sub/peste neutru redistribuie luminozitatea mediană; folosiți după expunere și înainte de evaluarea contrastului final.",
        ["Help.Plugins.Title"] = "Pluginuri native de procesare",
        ["Help.Plugins.Body"] = "Un plugin este un DLL Windows x64 care oferă unul sau mai multe procesoare de imagine float32. StarSim Core citește metadatele și schema parametrilor, apoi generează automat slidere Expert, resetarea și un panou detașabil.",
        ["Help.Plugins.Install.Title"] = "Instalare și activare",
        ["Help.Plugins.Install.Body"] = "Deschideți Pluginuri → Manager pluginuri → Instalează plugin, alegeți DLL-ul, activați pluginurile externe și reporniți. Procesoarele acceptate apar în modul Expert sub PLUGINURI.",
        ["Help.Plugins.Panel.Title"] = "Unde apare panoul",
        ["Help.Plugins.Panel.Body"] = "Procesoarele plugin sunt adăugate după modulele Tone integrate. Starea și parametrii lor participă la previzualizare, Anulare/Refacere, proiecte, preseturi personalizate și export.",
        ["Help.Plugins.Develop.Title"] = "Dezvoltarea unui plugin",
        ["Help.Plugins.Develop.Body"] = "Deschideți Pluginuri → Ghid dezvoltator plugin sau folderul sdk inclus în release. Acesta conține headerul ABI, proiectul CMake independent, README complet și exemplul RGB-to-B&W / Invert & Tint.",
        ["Help.Plugins.Security"] = "Pluginurile native rulează în procesul StarSim Core și nu sunt izolate. Instalați numai DLL-uri de încredere și păstrați toate dependențele lângă plugin.",
        ["Help.Footer"] = "Ctrl+F1 deschide acest ghid. Toate controalele și descrierile modulelor urmează limba selectată a aplicației.",

        // Etichetele parametrilor integrați
        ["Parameter.auto"] = "Aliniere automată",
        ["Parameter.redX"] = "Roșu X",
        ["Parameter.redY"] = "Roșu Y",
        ["Parameter.greenX"] = "Verde X",
        ["Parameter.greenY"] = "Verde Y",
        ["Parameter.blueX"] = "Albastru X",
        ["Parameter.blueY"] = "Albastru Y",
        ["Parameter.search"] = "Rază de căutare",
        ["Parameter.luminance"] = "Luminanță",
        ["Parameter.chrominance"] = "Crominanță",
        ["Parameter.detailProtection"] = "Protecția detaliilor fine",
        ["Parameter.threshold"] = "Prag",
        ["Parameter.iterations"] = "Iterații",
        ["Parameter.psfRadius"] = "Rază PSF",
        ["Parameter.strength"] = "Intensitate",
        ["Parameter.damping"] = "Atenuare",
        ["Parameter.amount"] = "Cantitate",
        ["Parameter.radius"] = "Rază",
        ["Parameter.fineAmount"] = "Cantitate fină",
        ["Parameter.fineRadius"] = "Rază fină",
        ["Parameter.broadAmount"] = "Cantitate largă",
        ["Parameter.broadRadius"] = "Rază largă",
        ["Parameter.edgeProtection"] = "Protecția muchiilor",
        ["Parameter.localAmount"] = "Contrast local",
        ["Parameter.localRadius"] = "Rază locală",
        ["Parameter.microAmount"] = "Microcontrast",
        ["Parameter.microRadius"] = "Rază micro",
        ["Parameter.whiteRed"] = "Balans de alb R",
        ["Parameter.whiteGreen"] = "Balans de alb G",
        ["Parameter.whiteBlue"] = "Balans de alb B",
        ["Parameter.temperature"] = "Temperatură",
        ["Parameter.tint"] = "Tentă",
        ["Parameter.vibrance"] = "Vibranță",
        ["Parameter.red"] = "Roșu",
        ["Parameter.green"] = "Verde",
        ["Parameter.blue"] = "Albastru",
        ["Parameter.brightness"] = "Luminozitate",
        ["Parameter.blackPoint"] = "Punct de negru",
        ["Parameter.whitePoint"] = "Punct de alb",
        ["Parameter.highlights"] = "Lumini",
        ["Parameter.shadows"] = "Umbre",
        ["Parameter.stops"] = "Expunere",
        ["Parameter.factor"] = "Contrast",
        ["Parameter.gamma"] = "Gama",
        ["Parameter.core.saturation.amount"] = "Saturație",
        ["Parameter.globalStrength"] = "Intensitate globală",
        ["Parameter.initialLayerWidth"] = "Lățime Gaussiană inițială",
        ["Parameter.linked"] = "Straturi Wavelet legate",
        ["Parameter.ultraFineLayerEnhancementFactor"] = "Amplificare strat 1",
        ["Parameter.fineLayerEnhancementFactor"] = "Amplificare strat 2",
        ["Parameter.smallLayerEnhancementFactor"] = "Amplificare strat 3",
        ["Parameter.mediumLayerEnhancementFactor"] = "Amplificare strat 4",
        ["Parameter.largeLayerEnhancementFactor"] = "Amplificare strat 5",
        ["Parameter.structureLayerEnhancementFactor"] = "Amplificare strat 6",
        ["Parameter.ultraFineLayerGaussianWidth"] = "Lățime Gaussiană strat 1",
        ["Parameter.fineLayerGaussianWidth"] = "Lățime Gaussiană strat 2",
        ["Parameter.smallLayerGaussianWidth"] = "Lățime Gaussiană strat 3",
        ["Parameter.mediumLayerGaussianWidth"] = "Lățime Gaussiană strat 4",
        ["Parameter.largeLayerGaussianWidth"] = "Lățime Gaussiană strat 5",
        ["Parameter.structureLayerGaussianWidth"] = "Lățime Gaussiană strat 6",
        ["Parameter.ultraFineGaussianWidth"] = "Lățime Gaussiană strat 1",
        ["Parameter.fineGaussianWidth"] = "Lățime Gaussiană strat 2",
        ["Parameter.smallGaussianWidth"] = "Lățime Gaussiană strat 3",
        ["Parameter.mediumGaussianWidth"] = "Lățime Gaussiană strat 4",
        ["Parameter.largeGaussianWidth"] = "Lățime Gaussiană strat 5",
        ["Parameter.structureGaussianWidth"] = "Lățime Gaussiană strat 6",
        ["Parameter.ultraFineLayerDenoise"] = "Reducere zgomot strat 1",
        ["Parameter.fineLayerDenoise"] = "Reducere zgomot strat 2",
        ["Parameter.smallLayerDenoise"] = "Reducere zgomot strat 3",
        ["Parameter.mediumLayerDenoise"] = "Reducere zgomot strat 4",
        ["Parameter.largeLayerDenoise"] = "Reducere zgomot strat 5",
        ["Parameter.structureLayerDenoise"] = "Reducere zgomot strat 6",
        ["Parameter.ultraFineDenoise"] = "Reducere zgomot strat 1",
        ["Parameter.fineDenoise"] = "Reducere zgomot strat 2",
        ["Parameter.smallDenoise"] = "Reducere zgomot strat 3",
        ["Parameter.mediumDenoise"] = "Reducere zgomot strat 4",
        ["Parameter.largeDenoise"] = "Reducere zgomot strat 5",
        ["Parameter.structureDenoise"] = "Reducere zgomot strat 6",
        ["Parameter.ultraFineLayerThreshold"] = "Prag strat 1",
        ["Parameter.fineLayerThreshold"] = "Prag strat 2",
        ["Parameter.smallLayerThreshold"] = "Prag strat 3",
        ["Parameter.mediumLayerThreshold"] = "Prag strat 4",
        ["Parameter.largeLayerThreshold"] = "Prag strat 5",
        ["Parameter.structureLayerThreshold"] = "Prag strat 6",
        ["Parameter.ultraFineThreshold"] = "Prag strat 1",
        ["Parameter.fineThreshold"] = "Prag strat 2",
        ["Parameter.smallThreshold"] = "Prag strat 3",
        ["Parameter.mediumThreshold"] = "Prag strat 4",
        ["Parameter.largeThreshold"] = "Prag strat 5",
        ["Parameter.structureThreshold"] = "Prag strat 6",
        ["Parameter.soloLayer"] = "Strat solo",
        ["Parameter.scaleScheme"] = "Schema scalelor",
        ["Parameter.stepIncrement"] = "Increment liniar",
        ["Parameter.backend"] = "Motor de descompunere",
        ["Parameter.decompositionBackend"] = "Motor de descompunere",
    };
}
